
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[
[],[]
]
};
var f,aa=this,fa=function(){if(null===ba){var a;a:{var b=aa.document,c=b.querySelector&&b.querySelector("script[nonce]");if(c){var d=c.nonce||c.getAttribute("nonce");if(d&&ea.test(d)){a=d;break a}}a=null}ba=a||""}return ba},ea=/^[\w+/_-]+[=]{0,2}$/,ba=null,ha=function(a,b){function c(){}c.prototype=b.prototype;a.wf=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.cf=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,
d)}};var ia=function(a,b){this.C=a;this.Ad=b};ia.prototype.Od=function(){return this.C};ia.prototype.getData=function(){return this.Ad};ia.prototype.getData=ia.prototype.getData;ia.prototype.getType=ia.prototype.Od;var ja=function(a){return"number"===typeof a&&0<=a&&isFinite(a)&&0===a%1||"string"===typeof a&&"-"!==a[0]&&a===""+parseInt(a,10)},la=function(){this.ma={};this.Da=!1};la.prototype.get=function(a){return this.ma["dust."+a]};la.prototype.set=function(a,b){!this.Da&&(this.ma["dust."+a]=b)};la.prototype.has=function(a){return this.ma.hasOwnProperty("dust."+a)};var ma=function(a){var b=[],c;for(c in a.ma)a.ma.hasOwnProperty(c)&&b.push(c.substr(5));return b};
la.prototype.remove=function(a){!this.Da&&delete this.ma["dust."+a]};la.prototype.M=function(){this.Da=!0};var v=function(a){this.qa=new la;this.i=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ja(b)?this.i[Number(b)]=a[Number(b)]:this.qa.set(b,a[b]))};f=v.prototype;f.toString=function(){for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};f.set=function(a,b){if("length"==a){if(!ja(b))throw"RangeError: Length property must be a valid integer.";this.i.length=Number(b)}else ja(a)?this.i[Number(a)]=b:this.qa.set(a,b)};
f.get=function(a){return"length"==a?this.length():ja(a)?this.i[Number(a)]:this.qa.get(a)};f.length=function(){return this.i.length};f.X=function(){for(var a=ma(this.qa),b=0;b<this.i.length;b++)a.push(b+"");return new v(a)};f.remove=function(a){ja(a)?delete this.i[Number(a)]:this.qa.remove(a)};f.pop=function(){return this.i.pop()};f.push=function(a){return this.i.push.apply(this.i,Array.prototype.slice.call(arguments))};f.shift=function(){return this.i.shift()};
f.splice=function(a,b,c){return new v(this.i.splice.apply(this.i,arguments))};f.unshift=function(a){return this.i.unshift.apply(this.i,Array.prototype.slice.call(arguments))};f.has=function(a){return ja(a)&&this.i.hasOwnProperty(a)||this.qa.has(a)};v.prototype.unshift=v.prototype.unshift;v.prototype.splice=v.prototype.splice;v.prototype.shift=v.prototype.shift;v.prototype.push=v.prototype.push;v.prototype.pop=v.prototype.pop;v.prototype.remove=v.prototype.remove;v.prototype.getKeys=v.prototype.X;
v.prototype.get=v.prototype.get;v.prototype.set=v.prototype.set;var na=function(){function a(a,b){c[a]=b}function b(){c={};h=!1}var c={},d,e,g={},h=!1,k={add:a,Zb:function(a,b,c){g[a]||(g[a]={});g[a][b]=c},create:function(g){var k={add:a,assert:function(a,b){if(!h){var k=c[a]||d;k&&k.apply(g,Array.prototype.slice.call(arguments,0));e&&e.apply(g,Array.prototype.slice.call(arguments,0))}},reset:b};k.add=k.add;k.assert=k.assert;k.reset=k.reset;return k},Ac:function(a){return g[a]?(b(),c=g[a],!0):!1},ra:function(a){d=a},sa:function(a){e=a},reset:b,Kc:function(a){h=
a}};k.add=k.add;k.addToCache=k.Zb;k.loadFromCache=k.Ac;k.registerDefaultPermission=k.ra;k.registerGlobalPermission=k.sa;k.reset=k.reset;k.setPermitAllAsserts=k.Kc;return k};var oa=function(){function a(a,c){if(b[a]){if(b[a].Ua+c>b[a].max)throw Error("Quota exceeded");b[a].Ua+=c}}var b={},c=void 0,d=void 0,e={qe:function(a){c=a},$b:function(){c&&a(c,1)},se:function(a){d=a},W:function(b){d&&a(d,b)},Me:function(a,c){b[a]=b[a]||{Ua:0};b[a].max=c},Nd:function(a){return b[a]&&b[a].Ua||0},reset:function(){b={}},ud:a};e.onFnConsume=e.qe;e.consumeFn=e.$b;e.onStorageConsume=e.se;e.consumeStorage=e.W;e.setMax=e.Me;e.getConsumed=e.Nd;e.reset=e.reset;e.consume=e.ud;return e};var pa=function(a,b,c){this.N=a;this.I=b;this.aa=c;this.i=new la};f=pa.prototype;f.add=function(a,b){this.i.Da||(this.N.W(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b))};f.set=function(a,b){this.i.Da||(this.aa&&this.aa.has(a)?this.aa.set(a,b):(this.N.W(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b)))};f.get=function(a){return this.i.has(a)?this.i.get(a):this.aa?this.aa.get(a):void 0};
f.has=function(a){return!!this.i.has(a)||!(!this.aa||!this.aa.has(a))};f.K=function(){return this.N};f.M=function(){this.i.M()};pa.prototype.has=pa.prototype.has;pa.prototype.get=pa.prototype.get;pa.prototype.set=pa.prototype.set;pa.prototype.add=pa.prototype.add;var qa=function(){},ra=function(a){return"function"==typeof a},sa=function(a){return"string"==typeof a},ta=function(a){return"number"==typeof a&&!isNaN(a)},ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},va=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a,b){if(!ta(a)||!ta(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},xa=function(a){return Math.round(Number(a))||
0},za=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ba=function(a){var b=[];if(ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ca=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Da=function(){return(new Date).getTime()},Ea=function(){this.prefix="gtm.";this.values={}};Ea.prototype.set=function(a,b){this.values[this.prefix+a]=b};Ea.prototype.get=function(a){return this.values[this.prefix+a]};Ea.prototype.contains=function(a){return void 0!==this.get(a)};
var Fa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ga=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ha=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ia=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Ja=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};var w=function(a,b){la.call(this);this.Bc=a;this.Kd=b};ha(w,la);var La=function(a,b){for(var c,d=0;d<b.length&&!(c=Ka(a,b[d]),c instanceof ia);d++);return c},Ka=function(a,b){var c=a.get(String(b[0]));if(!(c&&c instanceof w))throw"Attempting to execute non-function "+b[0]+".";return c.o.apply(c,[a].concat(b.slice(1)))};w.prototype.toString=function(){return this.Bc};w.prototype.getName=function(){return this.Bc};w.prototype.getName=w.prototype.getName;w.prototype.X=function(){return new v(ma(this))};
w.prototype.getKeys=w.prototype.X;w.prototype.o=function(a,b){var c,d={H:function(){return a},evaluate:function(b){var c=a;return ua(b)?Ka(c,b):b},Aa:function(b){return La(a,b)},K:function(){return a.K()},P:function(){c||(c=a.I.create(d));return c}};a.K().$b();return this.Kd.apply(d,Array.prototype.slice.call(arguments,1))};w.prototype.invoke=w.prototype.o;var Ma=function(){la.call(this)};ha(Ma,la);Ma.prototype.X=function(){return new v(ma(this))};Ma.prototype.getKeys=Ma.prototype.X;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Na=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Oa=function(a){if(null==a)return String(a);var b=Na.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Pa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Qa=function(a){if(!a||"object"!=Oa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Pa(a,"constructor")&&!Pa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Pa(a,b)},Ra=function(a,b){var c=b||("array"==Oa(a)?[]:{}),d;for(d in a)if(Pa(a,d)){var e=a[d];"array"==Oa(e)?("array"!=Oa(c[d])&&(c[d]=[]),c[d]=Ra(e,c[d])):Qa(e)?(Qa(c[d])||(c[d]={}),c[d]=Ra(e,c[d])):c[d]=e}return c};var Sa=function(a){if(a instanceof v){for(var b=[],c=a.length(),d=0;d<c;d++)a.has(d)&&(b[d]=Sa(a.get(d)));return b}if(a instanceof Ma){for(var e={},g=a.X(),h=g.length(),k=0;k<h;k++)e[g.get(k)]=Sa(a.get(g.get(k)));return e}return a instanceof w?function(){for(var b=Array.prototype.slice.call(arguments,0),c=0;c<b.length;c++)b[c]=Ta(b[c]);var d=new pa(oa(),na());return Sa(a.o.apply(a,[d].concat(b)))}:a},Ta=function(a){if(ua(a)){for(var b=[],c=0;c<a.length;c++)a.hasOwnProperty(c)&&(b[c]=Ta(a[c]));return new v(b)}if(Qa(a)){var d=
new Ma,e;for(e in a)a.hasOwnProperty(e)&&d.set(e,Ta(a[e]));return d}if("function"===typeof a)return new w("",function(b){for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;d++)c[d]=Sa(this.evaluate(c[d]));return Ta(a.apply(a,c))});var g=typeof a;if(null===a||"string"===g||"number"===g||"boolean"===g)return a};var Ua={control:function(a,b){return new ia(a,this.evaluate(b))},fn:function(a,b,c){var d=this.H(),e=this.evaluate(b);if(!(e instanceof v))throw"Error: non-List value given for Fn argument names.";var g=Array.prototype.slice.call(arguments,2);this.K().W(a.length+g.length);return new w(a,function(){return function(a){for(var b=new pa(d.N,d.I,d),c=Array.prototype.slice.call(arguments,0),h=0;h<c.length;h++)if(c[h]=this.evaluate(c[h]),c[h]instanceof ia)return c[h];for(var n=e.get("length"),p=0;p<n;p++)p<
c.length?b.set(e.get(p),c[p]):b.set(e.get(p),void 0);b.set("arguments",new v(c));var q=La(b,g);if(q instanceof ia)return"return"===q.C?q.getData():q}}())},list:function(a){var b=this.K();b.W(arguments.length);for(var c=new v,d=0;d<arguments.length;d++){var e=this.evaluate(arguments[d]);"string"===typeof e&&b.W(e.length?e.length-1:0);c.push(e)}return c},map:function(a){for(var b=this.K(),c=new Ma,d=0;d<arguments.length-1;d+=2){var e=this.evaluate(arguments[d])+"",g=this.evaluate(arguments[d+1]),h=
e.length;h+="string"===typeof g?g.length:1;b.W(h);c.set(e,g)}return c},undefined:function(){}};var Va=function(){this.N=oa();this.I=na();this.Ba=new pa(this.N,this.I)};f=Va.prototype;f.V=function(a,b){var c=new w(a,b);c.M();this.Ba.set(a,c)};f.Yb=function(a,b){Ua.hasOwnProperty(a)&&this.V(b||a,Ua[a])};f.K=function(){return this.N};f.ab=function(){this.N=oa();this.Ba.N=this.N};f.Je=function(){this.I=na();this.Ba.I=this.I};f.L=function(a,b){var c=Array.prototype.slice.call(arguments,0);return this.Bb(c)};
f.Bb=function(a){for(var b,c=0;c<arguments.length;c++){var d=Ka(this.Ba,arguments[c]);b=d instanceof ia||d instanceof w||d instanceof v||d instanceof Ma||null===d||void 0===d||"string"===typeof d||"number"===typeof d||"boolean"===typeof d?d:void 0}return b};f.M=function(){this.Ba.M()};Va.prototype.makeImmutable=Va.prototype.M;Va.prototype.run=Va.prototype.Bb;Va.prototype.execute=Va.prototype.L;Va.prototype.resetPermissions=Va.prototype.Je;Va.prototype.resetQuota=Va.prototype.ab;
Va.prototype.getQuota=Va.prototype.K;Va.prototype.addNativeInstruction=Va.prototype.Yb;Va.prototype.addInstruction=Va.prototype.V;var Wa=function(a){for(var b=[],c=0;c<a.length();c++)a.has(c)&&(b[c]=a.get(c));return b};var Xa={Qe:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" "),concat:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));for(d=1;d<arguments.length;d++)if(arguments[d]instanceof v)for(var e=arguments[d],g=0;g<e.length();g++)c.push(e.get(g));else c.push(arguments[d]);return new v(c)},every:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&
!b.o(a,this.get(d),d,this))return!1;return!0},filter:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&b.o(a,this.get(e),e,this)&&d.push(this.get(e));return new v(d)},forEach:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)this.has(d)&&b.o(a,this.get(d),d,this)},hasOwnProperty:function(a,b){return this.has(b)},indexOf:function(a,b,c){var d=this.length(),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var g=e;g<d;g++)if(this.has(g)&&this.get(g)===
b)return g;return-1},join:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));return c.join(b)},lastIndexOf:function(a,b,c){var d=this.length(),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var g=e;0<=g;g--)if(this.has(g)&&this.get(g)===b)return g;return-1},map:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&(d[e]=b.o(a,this.get(e),e,this));return new v(d)},pop:function(){return this.pop()},push:function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,
1))},reduce:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=0;else{if(0==d)throw"TypeError: Reduce on List with no elements.";for(var h=0;h<d;h++)if(this.has(h)){e=this.get(h);g=h+1;break}if(h==d)throw"TypeError: Reduce on List with no elements.";}for(h=g;h<d;h++)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reduceRight:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=d-1;else{if(0==d)throw"TypeError: ReduceRight on List with no elements.";for(var h=1;h<=d;h++)if(this.has(d-
h)){e=this.get(d-h);g=d-(h+1);break}if(h>d)throw"TypeError: ReduceRight on List with no elements.";}for(h=g;0<=h;h--)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reverse:function(){for(var a=Wa(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this},shift:function(){return this.shift()},slice:function(a,b,c){var d=this.length();void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,
c);for(var e=[],g=b;g<c;g++)e.push(this.get(g));return new v(e)},some:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&b.o(a,this.get(d),d,this))return!0;return!1},sort:function(a,b){var c=Wa(this);void 0===b?c.sort():c.sort(function(c,d){return Number(b.o(a,c,d))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)},splice:function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,1,arguments.length-1))},toString:function(){return this.toString()},
unshift:function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))}};var x={uc:{ADD:0,AND:1,APPLY:2,ASSIGN:3,BREAK:4,CASE:5,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,
PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42}},Ya="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),Za=new ia("break"),$a=new ia("continue");x.add=function(a,b){return this.evaluate(a)+this.evaluate(b)};x.and=function(a,b){return this.evaluate(a)&&this.evaluate(b)};
x.apply=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof v))throw"Error: Non-List argument given to Apply instruction.";if(null===a||void 0===a)throw"TypeError: Can't read property "+b+" of "+a+".";if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw"TypeError: "+a+"."+b+" is not a function.";}if("string"==typeof a){if(0<=va(Ya,b))return Ta(a[b].apply(a,Wa(c)));throw"TypeError: "+b+" is not a function";}if(a instanceof v){if(a.has(b)){var d=
a.get(b);if(d instanceof w){var e=Wa(c);e.unshift(this.H());return d.o.apply(d,e)}throw"TypeError: "+b+" is not a function";}if(0<=va(Xa.Qe,b))return e=Wa(c),e.unshift(this.H()),Xa[b].apply(a,e)}if(a instanceof w||a instanceof Ma){if(a.has(b)){d=a.get(b);if(d instanceof w)return e=Wa(c),e.unshift(this.H()),d.o.apply(d,e);throw"TypeError: "+b+" is not a function";}if("toString"==b)return a instanceof w?a.getName():a.toString();if("hasOwnProperty"==b)return a.has.apply(a,Wa(c))}throw"TypeError: Object has no '"+
b+"' property.";};x.assign=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw"Invalid key name given for assignment.";var c=this.H();if(!c.has(a))throw"Attempting to assign to undefined value "+b;var d=this.evaluate(b);c.set(a,d);return d};x["break"]=function(){return Za};x["case"]=function(a){for(var b=this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof ia)return d}};x["continue"]=function(){return $a};
x.Bd=function(a,b,c){var d=new v;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var g=[x.uc.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.H().set(a,this.evaluate(g))};x.Ed=function(a,b){return this.evaluate(a)/this.evaluate(b)};x.Hd=function(a,b){return this.evaluate(a)==this.evaluate(b)};x.Id=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
x.Ld=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.H();if("string"==typeof b)for(var e=0;e<b.length;e++){d.set(a,e);var g=this.Aa(c);if(g instanceof ia){if("break"==g.C)break;if("return"==g.C)return g}}else if(b instanceof Ma||b instanceof v||b instanceof w){var h=b.X(),k=h.length();for(e=0;e<k;e++)if(d.set(a,h.get(e)),g=this.Aa(c),g instanceof ia){if("break"==g.C)break;if("return"==g.C)return g}}};x.get=function(a){return this.H().get(this.evaluate(a))};
x.kc=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw"TypeError: cannot access property of "+a+".";a instanceof Ma||a instanceof v||a instanceof w?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ja(b)&&(c=a[b]));return c};x.Pd=function(a,b){return this.evaluate(a)>this.evaluate(b)};x.Qd=function(a,b){return this.evaluate(a)>=this.evaluate(b)};x.Xd=function(a,b){return this.evaluate(a)===this.evaluate(b)};x.Yd=function(a,b){return this.evaluate(a)!==this.evaluate(b)};
x["if"]=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.Aa(d);if(e instanceof ia)return e};x.fe=function(a,b){return this.evaluate(a)<this.evaluate(b)};x.he=function(a,b){return this.evaluate(a)<=this.evaluate(b)};x.ke=function(a,b){return this.evaluate(a)%this.evaluate(b)};x.multiply=function(a,b){return this.evaluate(a)*this.evaluate(b)};x.me=function(a){return-this.evaluate(a)};x.ne=function(a){return!this.evaluate(a)};
x.oe=function(a,b){return this.evaluate(a)!=this.evaluate(b)};x["null"]=function(){return null};x.or=function(a,b){return this.evaluate(a)||this.evaluate(b)};x.Gc=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c};x.Hc=function(a){return this.evaluate(a)};x.quote=function(a){return Array.prototype.slice.apply(arguments)};x["return"]=function(a){return new ia("return",this.evaluate(a))};
x.setProperty=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw"TypeError: Can't set property "+b+" of "+a+".";(a instanceof w||a instanceof v||a instanceof Ma)&&a.set(b,c);return c};x.Pe=function(a,b){return this.evaluate(a)-this.evaluate(b)};
x["switch"]=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!ua(b)||!ua(c))throw"Error: Malformed switch instruction.";for(var d,e=!1,g=0;g<b.length;g++)if(e||a===this.evaluate(b[g]))if(d=this.evaluate(c[g]),d instanceof ia){var h=d.C;if("break"==h)return;if("return"==h||"continue"==h)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof ia&&("return"==d.C||"continue"==d.C)))return d};
x.Re=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)};x["typeof"]=function(a){a=this.evaluate(a);return a instanceof w?"function":typeof a};x.undefined=function(){};x["var"]=function(a){for(var b=this.H(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}};
x["while"]=function(a,b,c,d){var e,g=this.evaluate(d);if(this.evaluate(c)&&(e=this.Aa(g),e instanceof ia)){if("break"==e.C)return;if("return"==e.C)return e}for(;this.evaluate(a);){e=this.Aa(g);if(e instanceof ia){if("break"==e.C)break;if("return"==e.C)return e}this.evaluate(b)}};var db=function(){this.sc=!1;this.F=new Va;ab(this);this.sc=!0};db.prototype.ce=function(){return this.sc};db.prototype.isInitialized=db.prototype.ce;db.prototype.L=function(a){this.F.I.Ac(String(a[0]))||(this.F.I.reset(),this.F.I.Kc(!0));return this.F.Bb(a)};db.prototype.execute=db.prototype.L;db.prototype.M=function(){this.F.M()};db.prototype.makeImmutable=db.prototype.M;
var ab=function(a){function b(a,b){e.F.Yb(a,String(b))}function c(a,b){e.F.V(String(d[a]),b)}var d=x.uc,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",x.add);c("AND",x.and);c("APPLY",x.apply);c("ASSIGN",x.assign);c("BREAK",x["break"]);c("CASE",x["case"]);c("CONTINUE",x["continue"]);c("DEFAULT",x["case"]);c("DEFN",x.Bd);c("DIVIDE",x.Ed);c("EQUALS",x.Hd);c("EXPRESSION_LIST",x.Id);c("FOR_IN",x.Ld);c("GET",x.get);c("GET_INDEX",
x.kc);c("GET_PROPERTY",x.kc);c("GREATER_THAN",x.Pd);c("GREATER_THAN_EQUALS",x.Qd);c("IDENTITY_EQUALS",x.Xd);c("IDENTITY_NOT_EQUALS",x.Yd);c("IF",x["if"]);c("LESS_THAN",x.fe);c("LESS_THAN_EQUALS",x.he);c("MODULUS",x.ke);c("MULTIPLY",x.multiply);c("NEGATE",x.me);c("NOT",x.ne);c("NOT_EQUALS",x.oe);c("NULL",x["null"]);c("OR",x.or);c("POST_DECREMENT",x.Gc);c("POST_INCREMENT",x.Gc);c("PRE_DECREMENT",x.Hc);c("PRE_INCREMENT",x.Hc);c("QUOTE",x.quote);c("RETURN",x["return"]);c("SET_PROPERTY",x.setProperty);
c("SUBTRACT",x.Pe);c("SWITCH",x["switch"]);c("TERNARY",x.Re);c("TYPEOF",x["typeof"]);c("VAR",x["var"]);c("WHILE",x["while"])};db.prototype.V=function(a,b){this.F.V(a,b)};db.prototype.addInstruction=db.prototype.V;db.prototype.K=function(){return this.F.K()};db.prototype.getQuota=db.prototype.K;db.prototype.ab=function(){this.F.ab()};db.prototype.resetQuota=db.prototype.ab;db.prototype.ra=function(a){this.F.I.ra(a)};db.prototype.sa=function(a){this.F.I.sa(a)};
db.prototype.Sa=function(a,b,c){this.F.I.Zb(a,b,c)};var eb=function(){this.Ya={}};eb.prototype.get=function(a){return this.Ya.hasOwnProperty(a)?this.Ya[a]:void 0};eb.prototype.add=function(a,b){if(this.Ya.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";if(!b)throw"Attempting to add an undefined function: "+a+".";var c=new w(a,function(){for(var a=Array.prototype.slice.call(arguments,0),c=0;c<a.length;c++)a[c]=this.evaluate(a[c]);return b.apply(this,a)});c.M();this.Ya[a]=c};
eb.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var z=window,A=document,fb=navigator,gb=A.currentScript&&A.currentScript.src,hb=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},ib=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},jb=function(a,b,c){var d=A.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ib(d,b);c&&(d.onerror=c);fa()&&d.setAttribute("nonce",fa());var e=A.getElementsByTagName("script")[0]||A.body||A.head;
e.parentNode.insertBefore(d,e);return d},kb=function(){if(gb){var a=gb.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},lb=function(a,b){var c=A.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=A.body&&A.body.lastChild||A.body||A.head;d.parentNode.insertBefore(c,d);ib(c,b);void 0!==a&&(c.src=a);return c},C=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=
function(){d.onerror=null;c&&c()};d.src=a},mb=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},nb=function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},F=function(a){z.setTimeout(a,0)},pb=function(a){var b=A.getElementById(a);if(b&&ob(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ob(document.all[a][c],"id")==a)return document.all[a][c];return b},ob=function(a,b){return a&&b&&a.attributes&&
a.attributes[b]?a.attributes[b].value:null},qb=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},rb=function(a){var b=A.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},tb=function(a){fb.sendBeacon&&fb.sendBeacon(a)||C(a)};var ub=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var vb=/:[0-9]+$/,wb=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")==b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},xb=function(a,b,c,d,e){var g,h=function(a){return a?a.replace(":","").toLowerCase():""},k=h(a.protocol)||h(z.location.protocol);b&&(b=String(b).toLowerCase());switch(b){case "protocol":g=k;break;case "host":g=(a.hostname||z.location.hostname).replace(vb,"").toLowerCase();
if(c){var l=/^www\d*\./.exec(g);l&&l[0]&&(g=g.substr(l[0].length))}break;case "port":g=String(Number(a.hostname?a.port:z.location.port)||("http"==k?80:"https"==k?443:""));break;case "path":g="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var m=g.split("/");0<=va(d||[],m[m.length-1])&&(m[m.length-1]="");g=m.join("/");break;case "query":g=a.search.replace("?","");e&&(g=wb(g,e));break;case "extension":var n=a.pathname.split(".");g=1<n.length?n[n.length-1]:"";g=g.split("/")[0];break;case "fragment":g=
a.hash.replace("#","");break;default:g=a&&a.href}return g},yb=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},G=function(a){var b=document.createElement("a");a&&(ub.test(a),b.href=a);var c=b.pathname;"/"!==c[0]&&(c="/"+c);var d=b.hostname.replace(vb,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var Bb=function(){this.Fa=new db;var a=new eb;a.addAll(zb());Ab(this,function(b){return a.get(b)})},zb=function(){return{callInWindow:Cb,callLater:Db,copyFromWindow:Eb,encodeURI:encodeURI,encodeURIComponent:encodeURIComponent,getReferrer:Fb,getUrl:Gb,getUrlFragment:Hb,isPlainObject:Ib,injectHiddenIframe:Jb,injectScript:Kb,logToConsole:Lb,queryPermission:Mb,removeUrlFragment:Nb,replaceAll:Ob,sendPixel:Pb,setInWindow:Qb}};Bb.prototype.L=function(a){return this.Fa.L(a)};Bb.prototype.execute=Bb.prototype.L;
var Ab=function(a,b){a.Fa.V("require",b)};Bb.prototype.ra=function(a){this.Fa.ra(a)};Bb.prototype.sa=function(a){this.Fa.sa(a)};Bb.prototype.Sa=function(a,b,c){this.Fa.Sa(a,b,c)};function Cb(a,b){for(var c=a.split("."),d=z,e=d[c[0]],g=1;e&&g<c.length;g++)d=e,e=e[c[g]];if("function"==Oa(e)){var h=[];for(g=1;g<arguments.length;g++)h.push(Sa(arguments[g]));e.apply(d,h)}}function Db(a){var b=this.H();F(function(){a instanceof w&&a.o(b)})}
function Eb(a){this.P().assert("read_globals",a);for(var b=a.split("."),c=z,d=0;d<b.length-1;d++)if(c=c[b[d]],void 0===c||null===c)return;return Ta(c[b[d]])}function Fb(){return A.referrer}function Gb(a,b,c,d){this.P().assert("get_url",a,d);var e=z.location.href,g;if(c&&c instanceof v){g=[];for(var h=0;h<c.length();h++){var k=c.get(h);"string"==typeof k&&g.push(k)}}return xb(G(e),a,b,g,d)}function Hb(a){return xb(G(a),"fragment")}function Ib(a){return a instanceof Ma}
function Jb(a,b){this.P().assert("inject_hidden_iframe",a);var c=this.H();lb(a,function(){b instanceof w&&b.o(c)})}var Rb={};
function Kb(a,b,c,d){this.P().assert("inject_script",a);var e=this.H(),g=function(){b instanceof w&&b.o(e)},h=function(){c instanceof w&&c.o(e)};d?Rb[d]?(Rb[d].onSuccess.push(g),Rb[d].onFailure.push(h)):(Rb[d]={onSuccess:[g],onFailure:[h]},g=function(){for(var a=Rb[d].onSuccess,b=0;b<a.length;b++)F(a[b]);a.push=function(a){F(a);return 0}},h=function(){for(var a=Rb[d].onFailure,b=0;b<a.length;b++)F(a[b]);Rb[d]=null},jb(a,g,h)):jb(a,g,h)}
function Lb(){try{this.P().assert("logging")}catch(c){return}for(var a=Array.prototype.slice.call(arguments,0),b=0;b<a.length;b++)a[b]=Sa(a[b]);console.log.apply(console,a)}function Nb(a){return yb(G(a))}function Ob(a,b,c){return a.replace(new RegExp(b,"g"),c)}function Pb(a,b,c){this.P().assert("send_pixel",a);var d=this.H();C(a,function(){b instanceof w&&b.o(d)},function(){c instanceof w&&c.o(d)})}
function Qb(a,b,c){this.P().assert("write_globals",a);for(var d=a.split("."),e=z,g=0;g<d.length-1;g++)if(e=e[d[g]],void 0===e)return!1;return void 0===e[d[g]]||c?(e[d[g]]=Sa(b),!0):!1}function Mb(a,b){try{return this.P().assert.apply(null,Array.prototype.slice.call(arguments,0)),!0}catch(c){return!1}};var oc,pc=[],qc=[],rc=[],sc=[],tc=[],uc={},vc,wc,xc,yc=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},zc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=!!uc[b],d={},e;for(e in a)a.hasOwnProperty(e)&&0===e.indexOf("vtp_")&&(d[c?e:e.substr(4)]=a[e]);return c?uc[b](d):oc(b,d)},Bc=function(a,b,c,d){c=c||[];d=d||qa;var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=Ac(a[g],b,c,d));return e},
Cc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=uc[b];return c?c.b||0:0},Ac=function(a,b,c,d){if(ua(a)){var e;switch(a[0]){case "function_id":return a[1];case "list":e=[];for(var g=1;g<a.length;g++)e.push(Ac(a[g],b,c,d));return e;case "macro":var h=a[1];if(c[h])return;var k=pc[h];if(!k||b(k))return;c[h]=!0;try{var l=Bc(k,b,c,d);e=zc(l);xc&&(e=xc.wd(e,l))}catch(E){d(h,E),e=!1}c[h]=!1;return e;case "map":e={};for(var m=1;m<a.length;m+=2)e[Ac(a[m],
b,c,d)]=Ac(a[m+1],b,c,d);return e;case "template":e=[];for(var n=!1,p=1;p<a.length;p++){var q=Ac(a[p],b,c,d);wc&&(n=n||q===wc.Ma);e.push(q)}return wc&&n?wc.xd(e):e.join("");case "escape":e=Ac(a[1],b,c,d);if(wc&&ua(a[1])&&"macro"===a[1][0]&&wc.de(a))return wc.xe(e);e=String(e);for(var r=2;r<a.length;r++)Sb[a[r]]&&(e=Sb[a[r]](e));return e;case "tag":var u=a[1];if(!sc[u])throw Error("Unable to resolve tag reference "+u+".");return e={gc:a[2],index:u};case "zb":var t={arg0:a[2],arg1:a[3],ignore_case:a[5]};
t["function"]=a[1];var B=Dc(t,b,c,d);a[4]&&(B=!B);return B;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Dc=function(a,b,c,d){try{return vc(Bc(a,b,c,d))}catch(e){JSON.stringify(a)}return null};var Gc=null,Kc=function(a){function b(a){for(var b=0;b<a.length;b++)d[a[b]]=!0}var c=[],d=[];Gc=Hc(a,Ic()||function(){});for(var e=0;e<qc.length;e++){var g=qc[e],h=Jc(g);if(h){for(var k=g.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(g.block||[])}else null===h&&b(g.block||[])}var m=[];for(e=0;e<sc.length;e++)c[e]&&!d[e]&&(m[e]=!0);return m},Jc=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Gc(b[c]);if(!d)return null===d?null:!1}var e=a.unless||[];for(c=0;c<e.length;c++){d=Gc(e[c]);if(null===
d)return null;if(d)return!1}return!0};var Hc=function(a,b){var c=[];return function(d){void 0===c[d]&&(c[d]=Dc(rc[d],a,void 0,b));return c[d]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Nc={},Oc=null;Nc.s="UA-2577926-1";Nc.Qa="am";var Pc="www.googletagmanager.com/gtm.js";Pc="www.googletagmanager.com/gtag/js";var Qc=Pc,Rc=null,Sc=null,Tc="//www.googletagmanager.com/a?id="+Nc.s+"&cv=1",Uc={},Vc={},Wc=function(){var a=Oc.sequence||0;Oc.sequence=a+1;return a};var N=function(a,b,c,d){return(2===Xc()||d||"http:"!=z.location.protocol?a:b)+c},Xc=function(){var a=kb(),b;if(1===a)a:{var c=Qc;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,g=1,h=A.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===g&&0===l.indexOf(d)&&(g=2)}}b=g}else b=a;return b};var Yc=!1;var Zc=function(a,b,c,d,e){if(c){var g=z._googWcmImpl||function(){g.q=g.q||[];g.q.push(arguments)};z._googWcmImpl=g;void 0===z._googWcmAk&&(z._googWcmAk=a);Yc||(jb(N("https://","http://","www.gstatic.com/wcm/loader.js")),Yc=!0);var h={ak:a,cl:b};void 0===d&&(h.autoreplace=c);g(2,d,h,c,0,new Date,e)}};var O=function(){var a=function(a){return{toString:function(){return a}}};return{Nb:a("convert_case_to"),Ob:a("convert_false_to"),Pb:a("convert_null_to"),Qb:a("convert_true_to"),Rb:a("convert_undefined_to"),fa:a("function"),Oc:a("instance_name"),Pc:a("live_only"),Qc:a("malware_disabled"),Rc:a("once_per_event"),Tb:a("once_per_load"),Ub:a("setup_tags"),Sc:a("tag_id"),Vb:a("teardown_tags")}}();var $c=new Ea,ad={},dd={set:function(a,b){Ra(bd(a,b),ad)},get:function(a){return cd(a,2)},reset:function(){$c=new Ea;ad={}}},cd=function(a,b){return 2!=b?$c.get(a):ed(a)},ed=function(a,b,c){var d=a.split(".");var e=function(a,b){for(var c=0;void 0!==a&&c<d.length;c++){if(null===a)return!1;a=a[d[c]]}return void 0!==a||1<c?a:b.length?e(fd(b.pop()),b):gd(d)};return e(ad.eventModel,[b,c]);return gd(d)},gd=function(a){for(var b=ad,c=0;c<a.length;c++){if(null===
b)return!1;if(void 0===b)break;b=b[a[c]]}return b};var fd=function(a){if(a){var b=gd(["gtag","targets",a]);return Qa(b)?b:void 0}},hd=function(a,b){function c(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(d[b]=null)}var d={};c(ad);delete d.eventModel;c(fd(a));c(fd(b));c(ad.eventModel);var e=[],g;for(g in d)d.hasOwnProperty(g)&&e.push(g);return e};
var id=function(a,b){$c.set(a,b);Ra(bd(a,b),ad)},bd=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c};var jd=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),kd={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},ld={cl:["ecl"],customPixels:["customScripts","html"],ecl:["cl"],html:["customScripts"],
customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]};
var md=function(a){var b=cd("gtm.whitelist");b=["google","gtagfl","lcl","oid","op"];var c=b&&Ja(Ba(b),kd),d=cd("gtm.blacklist")||cd("tagTypeBlacklist")||[];
jd.test(z.location&&z.location.hostname)&&(d=Ba(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&Ja(Ba(d),ld),g={};return function(h){var k=h&&h[O.fa];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];var l=Vc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>va(c,k))if(l&&0<l.length)for(var p=0;p<l.length;p++){if(0>va(c,l[p])){n=
!1;break a}}else{n=!1;break a}n=!0}m=n}var q=!1;if(d){var r;if(!(r=0<=va(e,k)))a:{for(var u=l||[],t=new Ea,B=0;B<e.length;B++)t.set(e[B],!0);for(var E=0;E<u.length;E++)if(t.get(u[E])){r=!0;break a}r=!1}q=r}return g[k]=!m||q}};var nd={wd:function(a,b){b[O.Nb]&&"string"===typeof a&&(a=1==b[O.Nb]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(O.Pb)&&null===a&&(a=b[O.Pb]);b.hasOwnProperty(O.Rb)&&void 0===a&&(a=b[O.Rb]);b.hasOwnProperty(O.Qb)&&!0===a&&(a=b[O.Qb]);b.hasOwnProperty(O.Ob)&&!1===a&&(a=b[O.Ob]);return a}};var od=function(a,b){this.ue=b};ha(od,Error);od.prototype.getParameters=function(){return this.ue};var pd=function(a){var b=Oc.zones;!b&&a&&(b=Oc.zones=a());return b},qd={active:!0,isWhitelisted:function(){return!0}};var rd=!1,sd=0,td=[];function ud(a){if(!rd){var b=A.createEventObject,c="complete"==A.readyState,d="interactive"==A.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){rd=!0;for(var e=0;e<td.length;e++)F(td[e])}td.push=function(){for(var a=0;a<arguments.length;a++)F(arguments[a]);return 0}}}function vd(){if(!rd&&140>sd){sd++;try{A.documentElement.doScroll("left"),ud()}catch(a){z.setTimeout(vd,50)}}}var wd=function(a){rd?a():td.push(a)};var yd=function(){function a(a){return!ta(a)||0>a?0:a}if(!Oc._li&&z.performance&&z.performance.timing){var b=z.performance.timing.navigationStart,c=ta(dd.get("gtm.start"))?dd.get("gtm.start"):0;Oc._li={cst:a(c-b),cbt:a(Rc-b)}}};var zd=!1,Ad=function(){return z.GoogleAnalyticsObject&&z[z.GoogleAnalyticsObject]};var Bd=function(a){z.GoogleAnalyticsObject||(z.GoogleAnalyticsObject=a||"ga");var b=z.GoogleAnalyticsObject;if(!z[b]){var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);z[b]=c}yd();return z[b]},Cd=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Ad();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var Gd=function(){return"&tc="+sc.filter(function(a){return a}).length},Hd="0.005000">Math.random(),Id=function(){var a=0,b=0;return{ee:function(){if(2>a)return!1;1E3<=Da()-b&&(a=0);return 2<=a},Ee:function(){1E3<=Da()-b&&(a=0);a++;b=Da()}}},Jd="",Kd=function(){Jd=[Tc,"&v=3&t=t","&pid="+wa(),"&rv="+Nc.Qa].join("")},Ld={},Md="",Nd=void 0,Od={},Pd={},Qd=void 0,Rd=null,Sd=1E3,Td=function(){var a=Nd;return void 0===a?"":[Jd,Ld[a]?"":"&es=1",Od[a],Gd(),Md,"&z=0"].join("")},Ud=function(){Qd&&
(z.clearTimeout(Qd),Qd=void 0);void 0===Nd||Ld[Nd]&&!Md||(Pd[Nd]||Rd.ee()||0>=Sd--?Pd[Nd]=!0:(Rd.Ee(),C(Td()),Ld[Nd]=!0,Md=""))},Vd=function(a,b,c){if(Hd&&!Pd[a]&&b){a!==Nd&&(Ud(),Nd=a);var d=c+String(b[O.fa]||"").replace(/_/g,"");Md=Md?Md+"."+d:"&tr="+d;Qd||(Qd=z.setTimeout(Ud,500));2022<=Td().length&&Ud()}};function Wd(a,b,c,d,e,g){var h=sc[a],k=Xd(a,b,c,d,e,g);if(!k)return null;var l=Ac(h[O.Ub],g.Z,[],Yd());if(l&&l.length){var m=l[0];k=Wd(m.index,b,k,1===m.gc?e:k,e,g)}return k}
function Xd(a,b,c,d,e,g){function h(){var b=Bc(k,g.Z,[],l);b.vtp_gtmOnSuccess=function(){Vd(g.id,sc[a],"5");c()};b.vtp_gtmOnFailure=function(){Vd(g.id,sc[a],"6");d()};b.vtp_gtmTagId=k.tag_id;if(k[O.Qc])d();else{Vd(g.id,k,"1");try{zc(b)}catch(E){Vd(g.id,
k,"7");e()}}}var k=sc[a];if(g.Z(k))return null;var l=Yd(),m=Ac(k[O.Vb],g.Z,[],l);if(m&&m.length){var n=m[0],p=Wd(n.index,b,c,d,e,g);if(!p)return null;c=p;d=2===n.gc?e:p}if(k[O.Tb]||k[O.Rc]){var q=k[O.Tb]?tc:b,r=c,u=d;if(!q[a]){h=Ga(h);var t=Zd(a,q,h);c=t.U;d=t.na}return function(){q[a](r,u)}}return h}
function Zd(a,b,c){var d=[],e=[];b[a]=$d(d,e,c);return{U:function(){b[a]=ae;for(var c=0;c<d.length;c++)d[c]()},na:function(){b[a]=be;for(var c=0;c<e.length;c++)e[c]()}}}function $d(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function ae(a){a()}function be(a,b){b()}function Yd(){return function(){}};function ce(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ga(function(){b++;d&&b>=c&&a()})},dd:function(){d=!0;b>=c&&a()}}}function de(a,b){var c,d=b.b,e=a.b;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.Mc,k=b.Mc;g=h>k?1:h<k?-1:0}return g}
function ee(a,b){if(!Hd)return;var c=function(a){var d=b.Z(sc[a])?"3":"4",g=Ac(sc[a][O.Ub],b.Z,[],qa);g&&g.length&&c(g[0].index);Vd(b.id,sc[a],d);var h=Ac(sc[a][O.Vb],b.Z,[],qa);h&&h.length&&c(h[0].index)};c(a);}var fe=!1;function Ic(){return function(){}};var ge=function(a,b){var c=yc(a,b),d;for(d in void 0)(void 0).hasOwnProperty(d)&&(c[d]=(void 0)[d]);sc.push(c);return sc.length-1};var he="allow_ad_personalization_signals cookie_domain cookie_expires cookie_name cookie_path custom_params event_callback event_timeout groups send_to send_page_view session_duration user_properties".split(" ");var ie={},ke=function(a){var b=Nc.s;return function(){var c=arguments[0];if(c&&(ie[c]||ie.all)){var d=a.apply(void 0,Array.prototype.slice.call(arguments,0));ie[c]&&je(b,c,ie[c],d);ie.all&&je(b,c,ie.all,d)}}};
function je(a,b,c,d){for(var e=0;e<c.length;e++){var g=void 0,h="An in-page policy denied the permission request";try{g=c[e].call(void 0,a,b,d),h+="."}catch(k){h="string"===typeof k?h+(": "+k):k instanceof Error?h+(": "+k.message):h+"."}if(!g)throw new od(b,{},h);}};var le=/[A-Z]+/,me=/\s/,ne=function(a){if(sa(a)&&(a=a.trim(),!me.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(le.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],Y:d}}}}};var oe=null,pe={},qe={},re;function se(){oe=oe||!Oc.gtagRegistered;Oc.gtagRegistered=!0;return oe}var te=function(a,b){var c={event:a};b&&(c.eventModel=Ra(b),b.event_callback&&(c.eventCallback=b.event_callback),b.event_timeout&&(c.eventTimeout=b.event_timeout));return c};
function ue(a){if(void 0===qe[a.id]){var b;switch(a.prefix){case "UA":b=ge("gtagua",{trackingId:a.id});break;case "AW":b=ge("gtagaw",{conversionId:a});break;case "DC":b=ge("gtagfl",{targetId:a.id});break;case "GF":b=ge("gtaggf",{conversionId:a});break;case "G":b=ge("get",{trackingId:a.id,isAutoTag:!0});break;case "HA":b=ge("gtagha",{conversionId:a});break;default:return}if(!re){var c=yc("v",{name:"send_to",dataLayerVersion:2});pc.push(c);re=["macro",pc.length-1]}var d={arg0:re,arg1:a.id,ignore_case:!1};
d[O.fa]="_lc";rc.push(d);var e={"if":[rc.length-1],add:[b]};e["if"]&&(e.add||e.block)&&qc.push(e);qe[a.id]=b}}
var we={config:function(a){var b=a[2]||{};if(2>a.length||!sa(a[1])||!Qa(b))return;var c=ne(a[1]);if(!c)return;se()?ue(c):ve();var d=c.id,e;for(e in pe)if(pe.hasOwnProperty(e)){var g=va(pe[e],d);0<=g&&pe[e].splice(g,1)}var h=c.id,k=b.groups||"default";k=k.toString().split(",");for(var l=0;l<k.length;l++)pe[k[l]]=pe[k[l]]||[],pe[k[l]].push(h);delete b.groups;id("gtag.targets."+c.id,void 0);id("gtag.targets."+c.id,Ra(b));var m={};m.send_to=c.id;return te("gtag.config",
m);},event:function(a){var b=a[1];if(sa(b)&&!(3<a.length)){var c;if(2<a.length){if(!Qa(a[2]))return;c=a[2]}var d=te(b,c);var e;var g=c,h=cd("gtag.fields.send_to",2);sa(h)||(h="send_to");var k=g&&g[h];void 0===k&&(k=cd(h,2),void 0===k&&(k="default"));if(sa(k)||ua(k)){for(var l,m=k.toString().replace(/\s+/g,"").split(","),n=[],p=0;p<m.length;p++)0<=m[p].indexOf("-")?n.push(m[p]):n=n.concat(pe[m[p]]||[]);l=n;for(var q={},r=0;r<l.length;++r){var u=
ne(l[r]);u&&(q[u.id]=u)}var t=[],B;for(B in q)if(q.hasOwnProperty(B)){var E=q[B];"AW"===E.prefix&&E.Y[1]&&t.push(E.containerId)}for(var y=0;y<t.length;++y)delete q[t[y]];var H=[],M;for(M in q)q.hasOwnProperty(M)&&H.push(q[M]);e=H}else e=void 0;if(!e)return;var D=se();D||ve();for(var L=[],K=0;D&&K<e.length;K++){var I=e[K];L.push(I.id);ue(I)}d.eventModel=d.eventModel||{};0<e.length?d.eventModel.send_to=L.join():delete d.eventModel.send_to;return d}},js:function(a){if(2==
a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(a){if(3===a.length){var b=a[1],c=a[2];ie[b]||(ie[b]=[]);ie[b].push(c)}},set:function(a){var b;2==a.length&&Qa(a[1])?b=Ra(a[1]):3==a.length&&sa(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=Ra(b),b.event="gtag.set",b._clear=!0,b}},ve=Ga(function(){});var xe=!1,ye=[];function ze(){if(!xe){xe=!0;for(var a=0;a<ye.length;a++)F(ye[a])}};var Ae=[],Be=!1,Ce=function(a){var b=a.eventCallback,c=Ga(function(){ra(b)&&F(function(){b(Nc.s)})}),d=a.eventTimeout;d&&z.setTimeout(c,Number(d));return c},De=function(){for(var a=!1;!Be&&0<Ae.length;){Be=!0;delete ad.eventModel;var b=Ae.shift();if(ra(b))try{b.call(dd)}catch(Pe){}else if(ua(b)){var c=b;if(sa(c[0])){var d=c[0].split("."),e=d.pop(),g=c.slice(1),h=cd(d.join("."),2);if(void 0!==h&&null!==h)try{h[e].apply(h,g)}catch(Pe){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{if(b.length&&sa(b[0])){var l=we[b[0]];if(l){b=l(b);break a}}b=void 0}if(!b){Be=!1;continue}}var m;var n=void 0,p=b,q=p._clear;for(n in p)p.hasOwnProperty(n)&&"_clear"!==n&&(q&&id(n,void 0),id(n,p[n]));var r=p.event;if(r){var u=p["gtm.uniqueEventId"];u||(u=Wc(),p["gtm.uniqueEventId"]=u,id("gtm.uniqueEventId",u));Sc=r;var t;var B,E,y=p,H=y.event,M=y["gtm.uniqueEventId"],D=Oc.zones;E=D?D.checkState(Nc.s,M):qd;if(E.active){var L=Ce(y);c:{var K=E.isWhitelisted;
if("gtm.js"==H){if(fe){B=!1;break c}fe=!0}var I=M,R=H;if(Hd&&!Pd[I]&&Nd!==I){Ud();Nd=I;Md="";var ka=Od,J=I,V,X=R;V=0===X.indexOf("gtm.")?encodeURIComponent(X):"*";ka[J]="&e="+V+"&eid="+I;Qd||(Qd=z.setTimeout(Ud,500))}var Y=md(K),P={id:M,name:H,callback:L||qa,Z:Y,Ha:[]};P.Ha=Kc(Y);for(var Aa,bb=P,Yb=ce(bb.callback),Ec=[],sb=[],cb=0;cb<sc.length;cb++)if(bb.Ha[cb]){var Qe=sc[cb];var Zb=Yb.add();try{var Re=Wd(cb,Ec,Zb,Zb,Zb,bb);Re?sb.push({Mc:cb,b:Cc(Qe),L:Re}):(ee(cb,bb),Zb())}catch(Pe){Zb()}}Yb.dd();sb.sort(de);for(var xd=0;xd<sb.length;xd++)sb[xd].L();Aa=0<sb.length;if("gtm.js"===H||"gtm.sync"===H)d:{}if(Aa){for(var Vg={__cl:!0,__ecl:!0,__evl:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Fc=0;Fc<P.Ha.length;Fc++)if(P.Ha[Fc]){var Te=sc[Fc];if(Te&&!Vg[Te[O.fa]]){B=!0;break c}}B=!1}else B=Aa}t=B?!0:!1}else t=!1;Sc=null;m=t}else m=!1;a=m||a}Be=!1}return!a},Ee=function(){var a=De();try{var b=z["dataLayer"].hide;if(b&&void 0!==b[Nc.s]&&b.end){b[Nc.s]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&
!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Fe=function(){var a=hb("dataLayer",[]),b=hb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};td.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ye.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ae.push.apply(Ae,b);300<this.length;)this.shift();return De()};Ae.push.apply(Ae,a.slice(0));
F(Ee)};var Ge={};Ge.Ma=new String("undefined");
var He=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Ge.Ma?b:a[d]);return c.join("")}};He.prototype.toString=function(){return this.resolve("undefined")};He.prototype.valueOf=He.prototype.toString;Ge.Tc=He;Ge.hb={};Ge.xd=function(a){return new He(a)};var Ie={};Ge.Fe=function(a,b){var c=Wc();Ie[c]=[a,b];return c};Ge.ac=function(a){var b=a?0:1;return function(a){var c=Ie[a];if(c&&"function"===typeof c[b])c[b]();Ie[a]=void 0}};Ge.de=function(a){for(var b=!1,c=!1,
d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};Ge.xe=function(a){if(a===Ge.Ma)return a;var b=Wc();Ge.hb[b]=a;return'google_tag_manager["'+Nc.s+'"].macro('+b+")"};Ge.je=function(a,b,c){a instanceof Ge.Tc&&(a=a.resolve(Ge.Fe(b,c)),b=qa);return{pb:a,U:b}};var Je=new Ea,Ke=function(a,b){function c(a){var b=G(a),c=xb(b,"protocol"),d=xb(b,"host",!0),e=xb(b,"port"),g=xb(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===c||"http"==c&&"80"==e||"https"==c&&"443"==e)c="web",e="default";return[c,d,e,g]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0};
function Le(a){var b=a.arg0,c=a.arg1;switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var d;a:{if(b){var e=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var g=0;g<e.length;g++)if(b[e[g]]){d=b[e[g]](c);break a}}catch(u){}}d=!1}return d;case "_ew":var h,k;h=String(b);k=String(c);var l=h.length-k.length;return 0<=l&&h.indexOf(k,l)==l;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);
case "_gt":return Number(b)>Number(c);case "_lc":var m;m=String(b).split(",");return 0<=va(m,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var n;var p=a.ignore_case?"i":void 0;try{var q=String(c)+p,r=Je.get(q);r||(r=new RegExp(c,p),Je.set(q,r));n=r.test(b)}catch(u){n=!1}return n;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Ke(b,c)}return!1};var Me=function(){return!1};function Ne(a,b){this.P().assert("read_data_layer",a);return Ta(cd(a,b||2))}function Oe(){return(new Date).getTime()}function Ue(a){return xa(Sa(a))}function Ve(a){return null===a?"null":void 0===a?"undefined":a.toString()}function We(a,b){return wa(a,b)}function Xe(a,b,c){if(!(a instanceof v))return null;for(var d=new Ma,e=!1,g=0;g<a.length();g++){var h=a.get(g);h instanceof Ma&&h.has(b)&&h.has(c)&&(d.set(h.get(b),h.get(c)),e=!0)}return e?d:null}
var Ye=function(){var a=new eb,b=zb();Me()&&(b.loadJavaScript=qa,b.loadIframe=qa);a.addAll({injectScript:b.injectScript,sendPixel:b.sendPixel,injectHiddenIframe:b.injectHiddenIframe,encodeUri:b.encodeURI,encodeUriComponent:b.encodeURIComponent,setInWindow:b.setInWindow,copyFromWindow:b.copyFromWindow,copyFromDataLayer:Ne,getUrl:b.getUrl,getDate:Oe,callLater:b.callLater,generateRandom:We,makeTableMap:Xe,makeString:Ve,makeInteger:Ue,logToConsole:b.logToConsole,queryPermission:b.queryPermission});return function(b){return a.get(b)}};var Ze;function $e(){var a=data.runtime||[];Ze=new Bb;oc=function(a,b){var c=new Ma,d;for(d in b)b.hasOwnProperty(d)&&c.set(d,Ta(b[d]));var e=Ze.L([a,c]);e instanceof ia&&"return"===e.C&&(e=e.getData());return Sa(e)};vc=Le;Ab(Ze,Ye());for(var b=0;b<a.length;b++){var c=a[b];if(!ua(c)||3>c.length){if(0===c.length)continue;break}Ze.L(c)}}
function af(a){var b={},c=function(a){throw bf(a,{},"The requested permission is not configured.");};Ze.ra(c);Ze.sa(ke(function(){var a=arguments[0];return a&&b[a]?b[a].apply(void 0,Array.prototype.slice.call(arguments,0)):{}}));for(var d in a)if(a.hasOwnProperty(d)){var e=a[d],g=!1,h;for(h in e)if(e.hasOwnProperty(h)){g=!0;var k=cf(h,e[h]);Ze.Sa(d,h,k.assert);b[h]||(b[h]=k.R)}g||Ze.Sa(d,"default",c)}}
function cf(a,b){var c=yc(a,b);c.vtp_permissionName=a;c.vtp_createPermissionError=bf;return zc(c)}function bf(a,b,c){return new od(a,b,c)};var df=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ef=function(a){return encodeURIComponent(a)},ff=function(a,b){if(!a)return!1;var c=xb(G(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var Q=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null},gf=function(a,b){Ra(a,b)},hf=function(a){return xa(a)},jf=function(a,b){return va(a,b)},kf=function(){return!1};var lf=function(a){var b={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||ob(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};b["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"";return b},mf=function(a){Oc.hasOwnProperty("autoEventsSettings")||(Oc.autoEventsSettings={});var b=Oc.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},nf=function(a,b,c,d){var e=mf(a),g=Fa(e,b,d);e[b]=
c(g)},of=function(a,b,c){var d=mf(a);return Fa(d,b,c)};var qf=function(a,b){if(!pf)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!A.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);return null},rf=!1;
if(A.querySelectorAll)try{var sf=A.querySelectorAll(":root");sf&&1==sf.length&&sf[0]==A.documentElement&&(rf=!0)}catch(a){}var pf=rf;var tf=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},wf=function(a,b,c,d){var e=uf(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=vf(e,function(a){return a.Fd},b);if(1===e.length)return e[0].id;e=vf(e,function(a){return a.ve},c);return e[0]?e[0].id:void 0}},zf=function(a,b,c,d,e,
g){c=c||"/";var h=d=d||"auto",k=c;if(xf.test(document.location.hostname)||"/"===k&&yf.test(h))return!1;g&&(b=encodeURIComponent(b));var l=b;l&&1200<l.length&&(l=l.substring(0,1200));b=l;var m=a+"="+b+"; path="+c+"; ";void 0!==e&&(m+="expires="+e.toUTCString()+"; ");if("auto"===d){var n=!1,p;a:{var q=[],r=document.location.hostname.split(".");if(4===r.length){var u=r[r.length-1];if(parseInt(u,10).toString()===u){p=["none"];break a}}for(var t=r.length-2;0<=t;t--)q.push(r.slice(t).join("."));q.push("none");
p=q}for(var B=p,E=0;E<B.length&&!n;E++)n=zf(a,b,c,B[E],e);return n}d&&"none"!==d&&(m+="domain="+d+";");var y=document.cookie;document.cookie=m;return y!=document.cookie||0<=tf(a).indexOf(b)};function vf(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function uf(a,b){for(var c=[],d=tf(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),Fd:1*k[0]||1,ve:1*k[1]||1}))}}return c}var yf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,xf=/(^|\.)doubleclick\.net$/i;var Af=function(){for(var a=fb.userAgent+(A.cookie||"")+(A.referrer||""),b=a.length,c=z.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Da()/1E3)].join(".")},Df=function(a,b,c,d){var e=Bf(b);return wf(a,e,Cf(c),d)};function Bf(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length}
function Cf(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1}function Ef(a,b){var c=""+Bf(a),d=Cf(b);1<d&&(c+="-"+d);return c};var Ff=["1"],Gf={},Kf=function(a,b,c){var d=Hf(a);Gf[d]||If(d,b,c)||(Jf(d,Af(),b,c),If(d,b,c))};function Jf(a,b,c,d){var e;e=["1",Ef(c,d),b].join(".");zf(a,e,d,c,new Date(Da()+7776E6))}function If(a,b,c){var d=Df(a,b,c,Ff);d&&(Gf[a]=d);return d}function Hf(a){return(a||"_gcl")+"_au"};function Lf(){for(var a=Mf,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Nf(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var Mf,Of,Pf=function(a){Mf=Mf||Nf();Of=Of||Lf();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,p=k&63;e||(p=64,d||(n=64));b.push(Mf[l],Mf[m],Mf[n],Mf[p])}return b.join("")},Qf=function(a){function b(b){for(;d<a.length;){var c=a.charAt(d++),e=Of[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("Unknown base64 encoding at char: "+c);}return b}Mf=Mf||Nf();Of=Of||
Lf();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Rf;function Sf(a,b){if(!a||b===A.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}var Tf=function(){var a=hb("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Uf=/(.*?)\*(.*?)\*(.*)/,Vf=/([^?#]+)(\?[^#]*)?(#.*)?/,Wf=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Yf=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Pf(String(d))))}var e=b.join("*");return["1",Xf(e),e].join("*")},Xf=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:
b),a].join("*"),d;if(!(d=Rf)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}Rf=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Rf[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},$f=function(){return function(a){var b=G(z.location.href),c=b.search.replace("?",""),d=wb(c,"_gl",!0)||"";a.query=Zf(d)||{};var e=xb(b,"fragment").match(Wf);a.fragment=Zf(e&&e[3]||"")||{}}},Zf=function(a){var b;b=void 0===b?3:b;try{if(a){var c=Uf.exec(a);if(c&&
"1"===c[1]){var d=c[3],e;a:{for(var g=c[2],h=0;h<b;++h)if(g===Xf(d,h)){e=!0;break a}e=!1}if(e){for(var k={},l=d?d.split("*"):[],m=0;m<l.length;m+=2)k[l[m]]=Qf(l[m+1]);return k}}}}catch(n){}};
function ag(a,b,c){function d(a){var b=a,c=Wf.exec(b),d=b;if(c){var e=c[2],g=c[4];d=c[1];g&&(d=d+e+g)}a=d;var h=a.charAt(a.length-1);a&&"&"!==h&&(a+="&");return a+l}c=void 0===c?!1:c;var e=Vf.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function bg(a,b,c){for(var d={},e={},g=Tf().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&Sf(k.domains,b)&&(k.fragment?Ha(e,k.callback()):Ha(d,k.callback()))}if(Ia(d)){var l=Yf(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],p=!1,q=0;q<n.length;q++){var r=n[q];if("_gl"===r.name){r.setAttribute("value",l);p=!0;break}}if(!p){var u=A.createElement("input");u.setAttribute("type","hidden");u.setAttribute("name","_gl");u.setAttribute("value",
l);a.appendChild(u)}}else if("post"===m){var t=ag(l,a.action);ub.test(t)&&(a.action=t)}}}else cg(l,a,!1)}if(!c&&Ia(e)){var B=Yf(e);cg(B,a,!0)}}function cg(a,b,c){if(b.href){var d=ag(a,b.href,void 0===c?!1:c);ub.test(d)&&(b.href=d)}}
var dg=function(a){try{var b;a:{for(var c=a.target||a.srcElement||{},d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||bg(e,e.hostname,!1)}}catch(h){}},eg=function(a){try{var b=a.target||a.srcElement||{};if(b.action){var c=xb(G(b.action),"host");bg(b,c,!0)}}catch(d){}},fg=function(a,b,c,d){var e=Tf();e.init||(mb(A,"mousedown",dg),mb(A,"keyup",dg),mb(A,"submit",eg),e.init=!0);var g={callback:a,
domains:b,fragment:"fragment"===c,forms:!!d};Tf().decorators.push(g)};var gg=/^\w+$/,hg=/^[\w-]+$/,ig=/^~?[\w-]+$/,jg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"},lg=function(a){var b=tf(a,A.cookie),c=[];if(!b||0==b.length)return c;for(var d=0;d<b.length;d++){var e=b[d].split(".");3==e.length&&"GCL"==e[0]&&e[1]&&c.push(e[2])}return kg(c)};function mg(a){return a&&"string"==typeof a&&a.match(gg)?a:"_gcl"}
var ng=function(a){if(a){if("string"==typeof a){var b=mg(a);return{dc:b,aw:b,gf:b,ha:b}}if(a&&"object"==typeof a)return{dc:mg(a.dc),aw:mg(a.aw),gf:mg(a.gf),ha:mg(a.ha)}}return{dc:"_gcl",aw:"_gcl",gf:"_gcl",ha:"_gcl"}},pg=function(){var a=G(z.location.href),b=xb(a,"query",!1,void 0,"gclid"),c=xb(a,"query",!1,void 0,"gclsrc"),d=xb(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||wb(e,"gclid");c=c||wb(e,"gclsrc")}return og(b,c,d)};
function og(a,b,c){var d={},e=function(a,b){d[b]||(d[b]=[]);d[b].push(a)};if(void 0!==a&&a.match(hg))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return d}
function qg(a,b){function c(a,b){var c=rg(a,d);c&&zf(c,b,g,e,k,!0)}b=b||{};var d=ng(b.prefix),e=b.domain||"auto",g=b.path||"/",h=Da(),k=new Date(h+7776E6),l=Math.round(h/1E3),m=function(a){return["GCL",l,a].join(".")};a.aw&&(!0===b.Af?c("aw",m("~"+a.aw[0])):c("aw",m(a.aw[0])));a.dc&&c("dc",m(a.dc[0]));a.gf&&c("gf",m(a.gf[0]));a.ha&&c("ha",m(a.ha[0]))}
var rg=function(a,b){var c=jg[a];if(void 0!==c){var d=b[a];if(void 0!==d)return d+c}},sg=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)},tg=function(a,b,c,d,e){if(ua(b)){var g=ng(e);fg(function(){for(var b={},c=0;c<a.length;++c){var d=rg(a[c],g);if(d){var e=tf(d,A.cookie);e.length&&(b[d]=e.sort()[e.length-1])}}return b},b,c,d)}},kg=function(a){return a.filter(function(a){return ig.test(a)})};var ug=/^\d+\.fls\.doubleclick\.net$/;function vg(a){var b=G(z.location.href),c=xb(b,"host",!1);if(c&&c.match(ug)){var d=xb(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
var wg=function(a){var b=vg("gclaw");if(b)return b.split(".");var c=ng(a);if("_gcl"==c.aw){var d=pg().aw||[];if(0<d.length)return d}var e=rg("aw",c);return e?lg(e):[]},xg=function(a){var b=vg("gcldc");if(b)return b.split(".");var c=ng(a);if("_gcl"==c.dc){var d=pg().dc||[];if(0<d.length)return d}var e=rg("dc",c);return e?lg(e):[]},yg=function(a){var b=ng(a);if("_gcl"==b.ha){var c=pg().ha||[];if(0<c.length)return c}return lg(b.ha+"_ha")},zg=function(){var a=vg("gac");if(a)return decodeURIComponent(a);
for(var b=[],c=A.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var g=c[e].match(d);g&&b.push({Fb:g[1],value:g[2]})}var h={};if(b&&b.length)for(var k=0;k<b.length;k++){var l=b[k].value.split(".");"1"==l[0]&&3==l.length&&l[1]&&(h[b[k].Fb]||(h[b[k].Fb]=[]),h[b[k].Fb].push({timestamp:l[1],Md:l[2]}))}var m=[],n;for(n in h)if(h.hasOwnProperty(n)){for(var p=[],q=h[n],r=0;r<q.length;r++)p.push(q[r].Md);p=kg(p);p.length&&m.push(n+":"+p.join(","))}return m.join(";")},Ag=function(a,
b,c){Kf(a,b,c);var d=Gf[Hf(a)],e=pg().dc||[];if(d&&0<e.length){var g=Oc.joined_au=Oc.joined_au||{},h=a||"_gcl";if(!g[h]){for(var k=!1,l=0;l<e.length;l++){var m="http://ad.doubleclick.net/ddm/regclk";m+="?gclid="+e[l]+"&auiddc="+d;tb(m);k=!0}if(k){var n=Hf(a);Gf[n]&&Jf(n,Gf[n],b,c);g[h]=!0}}}};var Cg={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Bg()};function Bg(){if(3===Nc.Qa.length)return"g";return"g";return"G"}function Dg(){return Me()?"s":"o";return"w"}
var Eg=function(a){var b=Nc.s.split("-"),c=b[0].toUpperCase(),d=Cg[c]||"i",e=a&&"GTM"===c?b[1]:"";return(3===Nc.Qa.length?"2"+Dg():"")+d+Nc.Qa+e};
var Fg=function(a){return!(void 0===a||null===a||0===(a+"").length)},Gg=function(a,b){var c;if(2===b.J)return a("ord",wa(1E11,1E13)),!0;if(3===b.J)return a("ord","1"),a("num",wa(1E11,1E13)),!0;if(4===b.J)return Fg(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.J)c="1";else if(6===b.J)c=b.Ic;else return!1;Fg(c)&&a("qty",c);Fg(b.lb)&&a("cost",b.lb);Fg(b.Gb)&&a("ord",b.Gb);return!0},Hg=encodeURIComponent,Ig=function(a,b){function c(a,b,c){g.hasOwnProperty(a)||(b+="",e+=";"+a+"="+(c?b:Hg(b)))}var d=a.nb,
e=a.protocol;e+=a.cb?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+Hg(d)+(";type="+Hg(a.ob))+(";cat="+Hg(a.ya));var g=a.zd||{},h;for(h in g)g.hasOwnProperty(h)&&(e+=";"+Hg(h)+"="+Hg(g[h]+""));if(Gg(c,a)){Fg(a.Ib)&&c("u",a.Ib);Fg(a.tran)&&c("tran",a.tran);c("gtm",Eg());!1===a.ad&&c("npa","1");if(a.kb){var k=xg(a.ka);k&&k.length&&c("gcldc",k.join("."));var l=wg(a.ka);l&&l.length&&c("gclaw",l.join("."));var m=zg();m&&c("gac",m);
Kf(a.ka);var n=Gf[Hf(a.ka)];n&&c("auiddc",n);}Fg(a.xb)&&c("prd",a.xb,!0);for(var p in a.Ja)a.Ja.hasOwnProperty(p)&&c(p,a.Ja[p]);e+=b||"";Fg(a.Za)&&c("~oref",a.Za);a.cb?lb(e+"?",a.U):C(e+"?",a.U,a.na)}else F(a.na)};
var Kg=function(a){if(a)try{if(a.conversion_id&&a.conversion_data){var b="/pagead/conversion/"+Jg(a.conversion_id)+"/?",c=Jg(JSON.stringify(a.conversion_data)),d="https://www.googletraveladservices.com/travel/flights/clk"+b+"conversion_data="+c;if(a.conversionLinkerEnabled){var e;a:{var g=ng(a.conversionPrefix);if("_gcl"==g.gf){var h=pg().gf||[];if(0<h.length){e=h;break a}}var k=rg("gf",g);e=k?lg(k):[]}var l=e;if(l&&l.length)for(var m=0;m<l.length;m++)d+="&gclgf="+Jg(l[m])}C(d,a.onSuccess,a.onFailure)}}catch(n){}},
Jg=function(a){return null===a||void 0===a||0===String(a).length?"":encodeURIComponent(String(a))};var Lg=!!z.MutationObserver,Mg=void 0,Ng=function(a){if(!Mg){var b=function(){var a=A.body;if(a)if(Lg)(new MutationObserver(function(){for(var a=0;a<Mg.length;a++)F(Mg[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;mb(a,"DOMNodeInserted",function(){b||(b=!0,F(function(){b=!1;for(var a=0;a<Mg.length;a++)F(Mg[a])}))})}};Mg=[];A.body?b():F(b)}Mg.push(a)};var Og=/\./g,Pg=/\*/g;var gh=function(a,b,c,d){mb(a,b,c,d)},hh=function(a,b){return z.setTimeout(a,b)},S=function(a,b,c){if(Me()){b&&F(b)}else return jb(a,b,c)},ih=function(){return z.location.href},jh=function(a){return xb(G(a),"fragment")},kh=function(a,b,c,d,e){return xb(a,b,c,d,e)},T=function(a,b){return cd(a,b||2)},lh=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return z["dataLayer"].push(a)},mh=function(a,b){z[a]=
b},U=function(a,b,c){b&&(void 0===z[a]||c&&!z[a])&&(z[a]=b);return z[a]},nh=function(a,b,c){return tf(a,b,void 0===c?!0:!!c)},oh=function(a,b,c){var d={prefix:a,path:b,domain:c},e=pg();qg(e,d)},ph=function(a,b,c,d){var e=$f(),g=Tf();g.data||(g.data={query:{},fragment:{}},e(g.data));var h={},k=g.data;k&&(Ha(h,k.query),Ha(h,k.fragment));for(var l=ng(b),m=0;m<a.length;++m){var n=a[m];if(void 0!==jg[n]){var p=rg(n,l),q=h[p];if(q){var r=Math.min(sg(q),Da()),
u;b:{for(var t=r,B=tf(p,A.cookie),E=0;E<B.length;++E)if(sg(B[E])>t){u=!0;break b}u=!1}u||zf(p,q,c,d,new Date(r+7776E6),!0)}}}var y={prefix:b,path:c,domain:d};qg(og(h.gclid,h.gclsrc),y);},qh=function(a,b,c,d,e){tg(a,b,c,d,e);},rh=function(a,b,c){var d;a:{var e;e=c||100;for(var g={},h=0;h<b.length;h++)g[b[h]]=!0;for(var k=a,l=0;k&&l<=e;l++){if(g[String(k.tagName).toLowerCase()]){d=
k;break a}k=k.parentElement}d=null}return d},sh=function(a,b){if(Me()){b&&F(b)}else lb(a,b)};
var th=function(a){var b=0;return b},uh=function(a){},vh=function(a){var b=!1;return b},wh=function(a,b){var c;a:{if(a&&
ua(a))for(var d=0;d<a.length;d++)if(a[d]&&b(a[d])){c=a[d];break a}c=void 0}return c},xh=function(a,b,c,d){nf(a,b,c,d)},yh=function(a,b,c){return of(a,b,c)},zh=function(a){return!!of(a,"init",!1)},Ah=function(a){mf(a).init=!0};
var Ch=function(a,b){return ed(a,b,void 0)},Dh=function(a,b,c,d){var e={config:a,gtm:Eg(void 0)};c&&(Kf(d),e.auiddc=Gf[Hf(d)]);b&&(e.loadInsecure=b);U("__dc_ns_processor",[]).push(e);S((b?"http":"https")+"://www.googletagmanager.com/dclk/ns/v1.js")};
var Eh=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Qc;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";if(b)for(var e in b)b[e]&&b.hasOwnProperty(e)&&(d+="&"+e+"="+encodeURIComponent(b[e]));S(N("https://","http://",d))};var Gh=Ge.je;
var Th=function(a,b,c){this.n=a;this.t=b;this.p=c},Uh=function(){this.c=1;this.e=[];this.p=null};function Vh(a){var b=Oc,c=b.gss=b.gss||{};return c[a]=c[a]||new Uh}var Wh=function(a,b){Vh(a).p=b},Xh=function(a,b,c){var d=Math.floor(Da()/1E3);Vh(a).e.push(new Th(b,d,c))},Yh=function(a){};var gi=window,hi=document,ii=function(a){var b=gi._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===gi["ga-disable-"+a])return!0;try{var c=gi.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=tf("AMP_TOKEN",hi.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return!1};var ni=function(a){if(1===Vh(a).c){Vh(a).c=2;var b=encodeURIComponent(a);jb(("http:"!=z.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},oi=function(a,b){};var W={a:{}};
W.a.gtagha=["google"],function(){function a(a){function b(a,b){void 0!==b&&c.push(a+"="+b)}if(void 0===a)return"";var c=[];b("hct_base_price",a.mc);b("hct_booking_xref",a.nc);b("hct_checkin_date",a.Td);b("hct_checkout_date",a.Ud);b("hct_currency_code",a.Vd);b("hct_partner_hotel_id",a.oc);b("hct_total_price",a.qc);return c.join(";")}function b(b,c,d,k){var e=encodeURIComponent(b),g=encodeURIComponent(a(c)),h="https://www.googletraveladservices.com/travel/clk/pagead/conversion/"+e+"/?data="+g;d&&(h+=
yg(k).map(function(a){return"&gclha="+encodeURIComponent(a)}).join(""));return h}function c(a,b,c,d){var e={};sa(a)?e.nc=a:"number"===typeof a&&(e.nc=String(a));sa(c)&&(e.Vd=c);sa(b)?e.qc=e.mc=b:"number"===typeof b&&(e.qc=e.mc=String(b));if(!ua(d)||0==d.length)return e;var g=d[0];if(!Qa(g))return e;sa(g.id)?e.oc=g.id:"number"===typeof g.id&&(e.oc=String(g.id));sa(g.start_date)&&(e.Td=g.start_date);sa(g.end_date)&&(e.Ud=g.end_date);return e}function d(a){var b=Sc,e=a.vtp_gtmOnSuccess,k=a.vtp_gtmOnFailure,
l=a.vtp_conversionId,m=l.containerId,n=function(a){return ed(a,m,l.id)},p=!1!==n("conversion_linker"),q=n("conversion_cookie_prefix");if("gtag.config"===b)p&&oh(q),F(e);else if("purchase"===b){var r=c(n("transaction_id"),n("value"),n("currency"),n("items"));d.Se(l.Y[0],r,p,q,e,k)}else F(k)}d.Se=function(a,c,d,k,l,m){if(/^\d+$/.test(a)){var e=b(a,c,d,k);C(e,l,m)}else F(m)};W.__gtagha=d;W.__gtagha.g="gtagha";W.__gtagha.h=!0;W.__gtagha.b=0}();W.a.e=["google"],function(){(function(a){W.__e=a;W.__e.g="e";W.__e.h=!0;W.__e.b=0})(function(){return Sc})}();


W.a.v=["google"],function(){(function(a){W.__v=a;W.__v.g="v";W.__v.h=!0;W.__v.b=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=T(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();




W.a.gtagaw=["google"],function(){var a=!1,b=[],c=["aw","dc"],d="send_to aw_remarketing aw_remarketing_only custom_params send_page_view language value currency transaction_id user_id conversion_linker conversion_cookie_prefix page_location page_referrer phone_conversion_number phone_conversion_callback phone_conversion_css_class items aw_merchant_id aw_feed_country aw_feed_language discount disable_merchant_reported_purchases allow_ad_personalization_signals".split(" "),e=function(a){var b=U("google_trackConversion"),
c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},g=function(){for(;0<b.length;)e(b.shift())},h=function(){a||(a=!0,yd(),S(N("https://","http://","www.googleadservices.com/pagead/conversion_async.js"),function(){g();b={push:e}},function(){g();a=!1}))},k=function(a){if(a){for(var b=[],c=0;c<a.length;++c){var d=a[c];d&&b.push({item_id:d.id,quantity:d.quantity,value:d.price,start_date:d.start_date,end_date:d.end_date})}return b}},l=function(a){var e=a.vtp_conversionId,g=Sc,l="gtag.config"==g,m=e.Y[0],
u=e.Y[1],t=void 0!==u,B=e.containerId,E=t?e.id:void 0,y=function(a){return ed(a,B,E)},H=!1!==y("conversion_linker"),M=y("conversion_cookie_prefix");if(l){var D=y("linker")||{};H&&((D.accept_incoming||!1!==D.accept_incoming&&D.domains)&&ph(c,M),oh(M));D.domains&&qh(c,D.domains,D.url_position,!!D.decorate_forms,M);if(t){var L=y("phone_conversion_number"),K=y("phone_conversion_callback"),I=y("phone_conversion_css_class"),R=y("phone_conversion_options");if(Me()){}else Zc(e.Y[0],e.Y[1],L,K||I,R)}}var ka=!1===y("aw_remarketing")||!1===y("send_page_view");if(!l||!t&&!ka)if(!0===y("aw_remarketing_only")&&(t=!1),!1!==y("allow_ad_personalization_signals")||t){var J={google_conversion_id:m,google_remarketing_only:!t,onload_callback:a.vtp_gtmOnSuccess,gtm_onFailure:a.vtp_gtmOnFailure,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:u,google_conversion_language:y("language"),
google_conversion_value:y("value"),google_conversion_currency:y("currency"),google_conversion_order_id:y("transaction_id"),google_user_id:y("user_id"),google_conversion_page_url:y("page_location"),google_conversion_referrer_url:y("page_referrer"),google_gtm:Eg(void 0)};!1===y("allow_ad_personalization_signals")&&(J.google_allow_ad_personalization_signals=!1);J.google_read_gcl_cookie_opt_out=!H;H&&M&&(Qa(M)?J.google_gcl_cookie_prefix=M.aw:J.google_gcl_cookie_prefix=M);var V=function(){var a=y("custom_params"),
b={event:g};if(ua(a)){for(var c=0;c<a.length;++c){var e=a[c],h=y(e);void 0!==h&&(b[e]=h)}return b}var k=y("eventModel");if(!k)return null;Ra(k,b);for(var l=0;l<d.length;++l)delete b[d[l]];return b}();V&&(J.google_custom_params=V);!t&&y("items")&&(J.google_gtag_event_data={items:y("items"),value:y("value")});if(t&&"purchase"==g){y("aw_merchant_id")&&(J.google_conversion_merchant_id=y("aw_merchant_id"),J.google_basket_feed_country=y("aw_feed_country"),J.google_basket_feed_language=y("aw_feed_language"),
J.google_basket_discount=y("discount"),J.google_basket_transaction_type=g,J.google_disable_merchant_reported_conversions=!0===y("disable_merchant_reported_purchases"),Me()&&(J.google_disable_merchant_reported_conversions=!0));var X=k(y("items"));X&&(J.google_conversion_items=X)}b.push(J)}h()};W.__gtagaw=l;W.__gtagaw.g="gtagaw";W.__gtagaw.h=!0;W.__gtagaw.b=0}();

W.a.get=["google"],function(){(function(a){W.__get=a;W.__get.g="get";W.__get.h=!0;W.__get.b=0})(function(a){if(a.vtp_isAutoTag){for(var b=String(a.vtp_trackingId),c=Sc||"",d={},e=0;e<he.length;e++){var g=Ch(he[e],b);void 0!==g&&(d[he[e]]=g)}var h=Ch("custom_params",b);if(ua(h))for(var k=0;k<h.length;k++){var l=h[k],m=Ch(l,b);void 0!==m&&(d[l]=m)}else{var n=T("eventModel");Ra(n,d)}var p=Ra(d,void 0);ni(b);Xh(b,c,p);Yh(b)}else{var q=a.vtp_settings,r=q.eventParameters,u=q.userProperties,t=Q(a.vtp_eventParameters,
"name","value");Ra(t,r);var B=Q(a.vtp_userProperties,"name","value");Ra(B,u);r.user_properties=u;var E=String(q.streamId),y=String(a.vtp_eventName);ni(E);Xh(E,y,r);Yh(E)}a.vtp_gtmOnSuccess()})}();


W.a.gtagfl=[],function(){function a(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{containerId:"DC-"+b[1],Nc:b[3]?a:"",Wc:b[1],Vc:b[3]||"",ya:b[4]||"",J:c}}}function b(a,b){function c(b,c,e){void 0!==e&&0!==(e+"").length&&d.push(b+c+":"+a(e+""))}var d=[],e=b("items")||[];if(ua(e))for(var g=0;g<e.length;g++){var n=e[g],p=g+1;c("i",p,n.id);c("p",p,n.price);c("q",p,n.quantity);
c("c",p,b("country"));c("l",p,b("language"))}return d.join("|")}function c(a,b,c){var d=/^u([1-9]\d?|100)$/,e=a("custom_map")||{},g=hd(b,c),h={},p={};if(Qa(e))for(var q in e)if(e.hasOwnProperty(q)&&d.test(q)){var r=e[q];sa(r)&&(h[q]=r)}for(var u=0;u<g.length;u++){var t=g[u];d.test(t)&&(h[t]=t)}for(var B in h)h.hasOwnProperty(B)&&(p[B]=a(h[B]));return p}var d=["aw","dc"];(function(a){W.__gtagfl=a;W.__gtagfl.g="gtagfl";W.__gtagfl.h=!0;W.__gtagfl.b=0})(function(e){var g=e.vtp_gtmOnSuccess,h=e.vtp_gtmOnFailure,
k=a(e.vtp_targetId);if(k){var l=function(a){return ed(a,k.containerId,k.Nc||void 0)},m=!1!==l("conversion_linker"),n=l("conversion_cookie_prefix"),p=l("dc_natural_search"),q=3===Xc();if("gtag.config"===Sc){var r=l("linker")||{};m&&((r.accept_incoming||!1!==r.accept_incoming&&r.domains)&&ph(d,n),oh(n),Ag(n,void 0,void 0));r.domains&&qh(d,r.domains,r.url_position,!!r.decorate_forms,n);if(p&&p.exclusion_parameters&&p.engines){}F(g)}else{var u=
{},t=l("dc_custom_params");if(Qa(t))for(var B in t)if(t.hasOwnProperty(B)){var E=t[B];void 0!==E&&null!==E&&(u[B]=E)}var y="";if(5===k.J||6===k.J)y=b(ef,l);var H=c(l,k.containerId,k.Nc),M=!0===l("allow_custom_scripts");if(Me()&&M){M=!1}var D={ya:k.ya,kb:m,ka:n,lb:l("value"),J:k.J,zd:u,nb:k.Wc,ob:k.Vc,na:h,U:g,Za:yb(G(ih())),xb:y,protocol:q?"http:":"https:",Ic:l("quantity"),cb:M,sessionId:l("session_id"),Gb:l("transaction_id"),
Ja:H,ad:!1!==l("allow_ad_personalization_signals")};Ig(D,void 0)}}else F(h)})}();
W.a.gtaggf=["google"],function(){var a=/.*\.google\.com(:\d+)?\/booking\/flights.*/,b=function(a){if(a){for(var b=[],c=0,g=0;g<a.length;++g){var h=a[g];!h||void 0!==h.category&&""!==h.category&&"FlightSegment"!==h.category||(b[c]={cabin:h.travel_class,fare_product:h.fare_product,booking_code:h.booking_code,flight_number:h.flight_number,origin:h.origin,destination:h.destination,departure_date:h.start_date},c++)}return b}};(function(a){W.__gtaggf=a;W.__gtaggf.g="gtaggf";W.__gtaggf.h=!0;W.__gtaggf.b=
0})(function(c){var d=Sc,e=c.vtp_gtmOnSuccess,g=c.vtp_gtmOnFailure,h=c.vtp_conversionId,k=h.Y[0],l=h.containerId,m=function(a){return ed(a,l,h.id)},n=!1!==m("conversion_linker"),p=m("conversion_cookie_prefix");if("gtag.config"===d)n&&oh(p),F(e);else{var q={conversion_id:k,onFailure:g,onSuccess:e,conversionLinkerEnabled:n,conversionPrefix:p};if("purchase"===d){var r=a.test(ih()),u={partner_id:k,trip_type:m("trip_type"),total_price:m("value"),currency:m("currency"),is_direct_booking:r,flight_segment:b(m("items"))},
t=m("passengers");t&&"object"===typeof t&&(u.passengers_total=t.total,u.passengers_adult=t.adult,u.passengers_child=t.child,u.passengers_infant_in_seat=t.infant_in_seat,u.passengers_infant_in_lap=t.infant_in_lap);q.conversion_data=u}Kg(q)}})}();


W.a.gtagua=["google"],function(){var a,b={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},c={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",
fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},d={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},e={cookie_name:1,cookie_expires:"duration",levels:1},g={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},
h=function(a,b,c,d){if(void 0!==c)if(g[b]&&(c=za(c)),"anonymize_ip"!=b||c||(c=void 0),1===a)d[k(b)]=c;else if(sa(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},k=function(a){return a&&sa(a)?a.replace(/(_[a-z])/g,function(a){return a[1].toUpperCase()}):a},l=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},m=function(a,e,g){var k={},m={},n={},p;var q=Ch("experiments",a);if(ua(q)){for(var t=[],r=0;r<q.length;r++){var u=q[r];if(void 0!=u){var B=u.id,ka=u.variant;void 0!=
B&&void 0!=ka&&t.push(String(B)+"."+String(ka))}}p=0<t.length?t.join("!"):void 0}else p=void 0;p&&l(m,"exp",p);var J=Ch("custom_map",a);if(Qa(J))for(var V in J)if(J.hasOwnProperty(V)&&/^(dimension|metric)\d+$/.test(V)&&void 0!=J[V]){var X=Ch(String(J[V]),a);void 0!==X&&l(m,V,X)}for(var Y=hd(a,void 0),P=0;P<Y.length;++P){var Z=Y[P],ca=Ch(Z,a);d.hasOwnProperty(Z)?h(d[Z],Z,ca,k):c.hasOwnProperty(Z)?h(c[Z],Z,ca,m):b.hasOwnProperty(Z)?h(b[Z],Z,ca,n):/^(dimension|metric|content_group)\d+$/.test(Z)&&h(1,
Z,ca,m)}var da=String(Sc);l(n,"cookieDomain","auto");l(m,"forceSSL",!0);var ya="general";0<=jf("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),da)?ya="ecommerce":0<=jf("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),da)?ya="engagement":"exception"==da&&(ya="error");l(k,"eventCategory",ya);0<=jf(["view_item","view_item_list",
"view_promotion","view_search_results"],da)&&l(m,"nonInteraction",!0);"login"==da||"sign_up"==da||"share"==da?l(k,"eventLabel",Ch("method",a)):"search"==da||"view_search_results"==da?l(k,"eventLabel",Ch("search_term",a)):"select_content"==da&&l(k,"eventLabel",Ch("content_type",a));var Aa=k.linker||{};if(Aa.accept_incoming||0!=Aa.accept_incoming&&Aa.domains)n.allowLinker=!0;if(!1===Ch("allow_display_features",a)||!1===Ch("allow_ad_personalization_signals",a))m.allowAdFeatures=!1;n.name=e;m["&gtm"]=
Eg(!0);m.hitCallback=g;k.T=m;k.cc=n;return k},n=function(a){function b(a){var b=Ra(a,void 0);b.list=a.list_name;b.listPosition=a.list_position;b.position=a.list_position||a.creative_slot;b.creative=a.creative_name;return b}function c(a){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&c.push(b(a[d]));return c.length?c:void 0}function d(a){return{id:e("transaction_id"),affiliation:e("affiliation"),revenue:e("value"),tax:e("tax"),shipping:e("shipping"),coupon:e("coupon"),list:e("list_name")||a}}for(var e=function(b){return ed(b,
a,void 0)},g=e("items"),h,k=0;g&&k<g.length&&!(h=g[k].list_name);k++);var m=e("custom_map");if(Qa(m))for(k=0;g&&k<g.length;++k){var n=g[k],p;for(p in m)m.hasOwnProperty(p)&&/^(dimension|metric)\d+$/.test(p)&&void 0!=m[p]&&l(n,p,n[m[p]])}var q=null,r=Sc,u=e("promotions");"purchase"==r||"refund"==r?q={action:r,xa:d(),oa:c(g)}:"add_to_cart"==r?q={action:"add",oa:c(g)}:"remove_from_cart"==r?q={action:"remove",oa:c(g)}:"view_item"==r?q={action:"detail",xa:d(h),oa:c(g)}:"view_item_list"==r?q={action:"impressions",
Zd:c(g)}:"view_promotion"==r?q={action:"promo_view",yb:c(u)}:"select_content"==r&&u&&0<u.length?q={action:"promo_click",yb:c(u)}:"select_content"==r?q={action:"click",xa:{list:e("list_name")||h},oa:c(g)}:"begin_checkout"==r||"checkout_progress"==r?q={action:"checkout",oa:c(g),xa:{step:"begin_checkout"==r?1:e("checkout_step"),option:e("checkout_option")}}:"set_checkout_option"==r&&(q={action:"checkout_option",xa:{step:e("checkout_step"),option:e("checkout_option")}});q&&(q.ff=e("currency"));return q},
p={},q=function(a,b){var c=p[a];p[a]=Ra(b,void 0);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(d in c)if(c.hasOwnProperty(d)&&c[d]!==b[d])return!0;return!1},r=function(b){var c=b.vtp_trackingId,d=Bd(void 0),g="gtag_"+c.split("-").join("_"),p=function(a){var b=[].slice.call(arguments,0);b[0]=g+"."+b[0];d.apply(window,b)},r=function(){var a=function(a,b){for(var c=0;b&&c<b.length;c++)p(a,b[c])},b=n(c);if(b){var d=b.action;if("impressions"==d)a("ec:addImpression",b.Zd);
else if("promo_click"==d||"promo_view"==d){var e=b.yb;a("ec:addPromo",b.yb);e&&0<e.length&&"promo_click"==d&&p("ec:setAction",d)}else a("ec:addProduct",b.oa),p("ec:setAction",d,b.xa)}},u=function(){if(Me()){}else{var a=Ch("optimize_id",c);a&&(p("require",a,{dataLayer:"dataLayer"}),p("require","render"))}},D=m(c,g,b.vtp_gtmOnSuccess);q(g,D.cc)&&d(function(){Ad()&&Ad().remove(g)});d("create",c,D.cc);(function(){var a=
Ch("custom_map",c);d(function(){if(Qa(a)){var b=D.T,c=Ad().getByName(g),d;for(d in a)if(a.hasOwnProperty(d)&&/^(dimension|metric)\d+$/.test(d)&&void 0!=a[d]){var e=c.get(k(a[d]));l(b,d,e)}}})})();(function(a){if(a){var b={};if(Qa(a))for(var c in e)e.hasOwnProperty(c)&&h(e[c],c,a[c],b);p("require","linkid",b)}})(D.linkAttribution);var L=D.linker;L&&L.domains&&Cd(g+".",L.domains,!!L.use_anchor,!!L.decorate_forms);var K=function(a,b,c){c&&(b=""+b);D.T[a]=b},I=Sc;"page_view"==I?(u(),p("send","pageview",
D.T)):"gtag.config"==I?(u(),0!=D.sendPageView&&p("send","pageview",D.T)):"screen_view"==I?p("send","screenview",D.T):"timing_complete"==I?(K("timingCategory",D.eventCategory,!0),K("timingVar",D.name,!0),K("timingValue",xa(D.value)),void 0!==D.eventLabel&&K("timingLabel",D.eventLabel,!0),p("send","timing",D.T)):"exception"==I?p("send","exception",D.T):(0<=jf("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),
I)&&(p("require","ec","ec.js"),r()),K("eventCategory",D.eventCategory,!0),K("eventAction",D.eventAction||I,!0),void 0!==D.eventLabel&&K("eventLabel",D.eventLabel,!0),void 0!==D.value&&K("eventValue",xa(D.value)),p("send","event",D.T));a||(a=!0,yd(),S("https://www.google-analytics.com/analytics.js",function(){Ad().loaded||b.vtp_gtmOnFailure()},b.vtp_gtmOnFailure))};W.__gtagua=r;W.__gtagua.g="gtagua";
W.__gtagua.h=!0;W.__gtagua.b=0}();


var pi={};pi.macro=function(a){if(Ge.hb.hasOwnProperty(a))return Ge.hb[a]},pi.onHtmlSuccess=Ge.ac(!0),pi.onHtmlFailure=Ge.ac(!1);pi.dataLayer=dd;pi.callback=function(a){Uc.hasOwnProperty(a)&&ra(Uc[a])&&Uc[a]();delete Uc[a]};pi.jd=function(){Oc[Nc.s]=pi;Vc=W.a;wc=wc||Ge;xc=nd};
pi.$d=function(){Oc=z.google_tag_manager=z.google_tag_manager||{};if(Oc[Nc.s]){var a=Oc.zones;a&&a.unregisterChild(Nc.s)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)pc.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)sc.push(e[g]);for(var h=b.predicates||[],k=0;k<h.length;k++)rc.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],p={},q=0;q<n.length;q++)p[n[q][0]]=Array.prototype.slice.call(n[q],1);qc.push(p)}uc=W;var r=data.permissions||{};$e();af(r);pi.jd();
Fe();rd=!1;sd=0;if("interactive"==A.readyState&&!A.createEventObject||"complete"==A.readyState)ud();else{mb(A,"DOMContentLoaded",ud);mb(A,"readystatechange",ud);if(A.createEventObject&&A.documentElement.doScroll){var u=!0;try{u=!z.frameElement}catch(B){}u&&vd()}mb(z,"load",ud)}xe=!1;"complete"===A.readyState?ze():mb(z,"load",ze);
a:{if(!Hd)break a;Kd();Nd=void 0;Od={};Ld={};Qd=void 0;Pd={};Md="";Rd=Id();z.setInterval(Kd,864E5);}Rc=(new Date).getTime()}};pi.$d();

})()
