caches:
  maplet_WorldCountry:
    grids:
    - webmercator
    sources:
    - maplet_WorldCountry
  osm_cache:
    grids:
    - webmercator
    sources:
    - osm_wms
globals: null
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
layers:
- name: osm
  sources:
  - osm_cache
  title: Omniscale OSM WMS - osm.omniscale.net
- name: maplet_WorldCountry
  sources:
  - maplet_WorldCountry
  title: maplet_WorldCountry
services:
  demo: null
  kml:
    use_grid_names: true
  tms:
    origin: nw
    use_grid_names: true
  wms:
    md:
      abstract: This is a minimal MapProxy example.
      title: MapProxy WMS Proxy
  wmts: null
sources:
  maplet_WorldCountry:
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 0
    req:
      layers: lyr_WorldCountry
      url: http://webgis.pub:8080/cgi-bin/mapserv?map=/gdata/mfile_world.map
    type: wms
  osm_wms:
    req:
      layers: osm
      url: http://osm.omniscale.net/proxy/service?
    type: wms
