
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[
[],[]
]
};
var f,aa=this,ha=function(){if(null===ea){var a;a:{var b=aa.document,c=b.querySelector&&b.querySelector("script[nonce]");if(c){var d=c.nonce||c.getAttribute("nonce");if(d&&fa.test(d)){a=d;break a}}a=null}ea=a||""}return ea},fa=/^[\w+/_-]+[=]{0,2}$/,ea=null,ia=function(a,b){function c(){}c.prototype=b.prototype;a.tf=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.$e=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,
d)}};var v=function(a,b){this.C=a;this.yd=b};v.prototype.Md=function(){return this.C};v.prototype.getData=function(){return this.yd};v.prototype.getData=v.prototype.getData;v.prototype.getType=v.prototype.Md;var ka=function(a){return"number"===typeof a&&0<=a&&isFinite(a)&&0===a%1||"string"===typeof a&&"-"!==a[0]&&a===""+parseInt(a,10)},la=function(){this.ka={};this.Ba=!1};la.prototype.get=function(a){return this.ka["dust."+a]};la.prototype.set=function(a,b){!this.Ba&&(this.ka["dust."+a]=b)};la.prototype.has=function(a){return this.ka.hasOwnProperty("dust."+a)};var ma=function(a){var b=[],c;for(c in a.ka)a.ka.hasOwnProperty(c)&&b.push(c.substr(5));return b};
la.prototype.remove=function(a){!this.Ba&&delete this.ka["dust."+a]};la.prototype.M=function(){this.Ba=!0};var w=function(a){this.na=new la;this.i=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ka(b)?this.i[Number(b)]=a[Number(b)]:this.na.set(b,a[b]))};f=w.prototype;f.toString=function(){for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};f.set=function(a,b){if("length"==a){if(!ka(b))throw"RangeError: Length property must be a valid integer.";this.i.length=Number(b)}else ka(a)?this.i[Number(a)]=b:this.na.set(a,b)};
f.get=function(a){return"length"==a?this.length():ka(a)?this.i[Number(a)]:this.na.get(a)};f.length=function(){return this.i.length};f.V=function(){for(var a=ma(this.na),b=0;b<this.i.length;b++)a.push(b+"");return new w(a)};f.remove=function(a){ka(a)?delete this.i[Number(a)]:this.na.remove(a)};f.pop=function(){return this.i.pop()};f.push=function(a){return this.i.push.apply(this.i,Array.prototype.slice.call(arguments))};f.shift=function(){return this.i.shift()};
f.splice=function(a,b,c){return new w(this.i.splice.apply(this.i,arguments))};f.unshift=function(a){return this.i.unshift.apply(this.i,Array.prototype.slice.call(arguments))};f.has=function(a){return ka(a)&&this.i.hasOwnProperty(a)||this.na.has(a)};w.prototype.unshift=w.prototype.unshift;w.prototype.splice=w.prototype.splice;w.prototype.shift=w.prototype.shift;w.prototype.push=w.prototype.push;w.prototype.pop=w.prototype.pop;w.prototype.remove=w.prototype.remove;w.prototype.getKeys=w.prototype.V;
w.prototype.get=w.prototype.get;w.prototype.set=w.prototype.set;var na=function(){function a(a,b){c[a]=b}function b(){c={};g=!1}var c={},d,e={},g=!1,h={add:a,Xb:function(a,b,c){e[a]||(e[a]={});e[a][b]=c},create:function(e){var h={add:a,assert:function(a,b){if(!g){var h=c[a]||d;h&&h.apply(e,Array.prototype.slice.call(arguments,0))}},reset:b};h.add=h.add;h.assert=h.assert;h.reset=h.reset;return h},yc:function(a){return e[a]?(b(),c=e[a],!0):!1},oa:function(a){d=a},reset:b,Ic:function(a){g=a}};h.add=h.add;h.addToCache=h.Xb;h.loadFromCache=h.yc;h.registerDefaultPermission=
h.oa;h.reset=h.reset;h.setPermitAllAsserts=h.Ic;return h};var oa=function(){function a(a,c){if(b[a]){if(b[a].Ra+c>b[a].max)throw Error("Quota exceeded");b[a].Ra+=c}}var b={},c=void 0,d=void 0,e={ne:function(a){c=a},Yb:function(){c&&a(c,1)},oe:function(a){d=a},U:function(b){d&&a(d,b)},Je:function(a,c){b[a]=b[a]||{Ra:0};b[a].max=c},Ld:function(a){return b[a]&&b[a].Ra||0},reset:function(){b={}},sd:a};e.onFnConsume=e.ne;e.consumeFn=e.Yb;e.onStorageConsume=e.oe;e.consumeStorage=e.U;e.setMax=e.Je;e.getConsumed=e.Ld;e.reset=e.reset;e.consume=e.sd;return e};var pa=function(a,b,c){this.N=a;this.I=b;this.Y=c;this.i=new la};f=pa.prototype;f.add=function(a,b){this.i.Ba||(this.N.U(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b))};f.set=function(a,b){this.i.Ba||(this.Y&&this.Y.has(a)?this.Y.set(a,b):(this.N.U(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b)))};f.get=function(a){return this.i.has(a)?this.i.get(a):this.Y?this.Y.get(a):void 0};
f.has=function(a){return!!this.i.has(a)||!(!this.Y||!this.Y.has(a))};f.K=function(){return this.N};f.M=function(){this.i.M()};pa.prototype.has=pa.prototype.has;pa.prototype.get=pa.prototype.get;pa.prototype.set=pa.prototype.set;pa.prototype.add=pa.prototype.add;var qa=function(){},ra=function(a){return"function"==typeof a},sa=function(a){return"string"==typeof a},ta=function(a){return"number"==typeof a&&!isNaN(a)},ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},va=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a,b){if(!ta(a)||!ta(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},ya=function(a){return Math.round(Number(a))||
0},Aa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ba=function(a){var b=[];if(ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ca=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Da=function(){return(new Date).getTime()},Ea=function(){this.prefix="gtm.";this.values={}};Ea.prototype.set=function(a,b){this.values[this.prefix+a]=b};Ea.prototype.get=function(a){return this.values[this.prefix+a]};Ea.prototype.contains=function(a){return void 0!==this.get(a)};
var Fa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ga=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ha=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ia=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};var x=function(a,b){la.call(this);this.zc=a;this.Id=b};ia(x,la);var Ka=function(a,b){for(var c,d=0;d<b.length&&!(c=Ja(a,b[d]),c instanceof v);d++);return c},Ja=function(a,b){var c=a.get(String(b[0]));if(!(c&&c instanceof x))throw"Attempting to execute non-function "+b[0]+".";return c.o.apply(c,[a].concat(b.slice(1)))};x.prototype.toString=function(){return this.zc};x.prototype.getName=function(){return this.zc};x.prototype.getName=x.prototype.getName;x.prototype.V=function(){return new w(ma(this))};
x.prototype.getKeys=x.prototype.V;x.prototype.o=function(a,b){var c,d={F:function(){return a},evaluate:function(b){var c=a;return ua(b)?Ja(c,b):b},xa:function(b){return Ka(a,b)},K:function(){return a.K()},ya:function(){c||(c=a.I.create(d));return c}};a.K().Yb();return this.Id.apply(d,Array.prototype.slice.call(arguments,1))};x.prototype.invoke=x.prototype.o;var La=function(){la.call(this)};ia(La,la);La.prototype.V=function(){return new w(ma(this))};La.prototype.getKeys=La.prototype.V;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ma=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Na=function(a){if(null==a)return String(a);var b=Ma.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Oa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Pa=function(a){if(!a||"object"!=Na(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Oa(a,"constructor")&&!Oa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Oa(a,b)},Qa=function(a,b){var c=b||("array"==Na(a)?[]:{}),d;for(d in a)if(Oa(a,d)){var e=a[d];"array"==Na(e)?("array"!=Na(c[d])&&(c[d]=[]),c[d]=Qa(e,c[d])):Pa(e)?(Pa(c[d])||(c[d]={}),c[d]=Qa(e,c[d])):c[d]=e}return c};var Ra=function(a){if(a instanceof w){for(var b=[],c=a.length(),d=0;d<c;d++)a.has(d)&&(b[d]=Ra(a.get(d)));return b}if(a instanceof La){for(var e={},g=a.V(),h=g.length(),k=0;k<h;k++)e[g.get(k)]=Ra(a.get(g.get(k)));return e}return a instanceof x?function(){for(var b=Array.prototype.slice.call(arguments,0),c=0;c<b.length;c++)b[c]=Sa(b[c]);var d=new pa(oa(),na());return Ra(a.o.apply(a,[d].concat(b)))}:a},Sa=function(a){if(ua(a)){for(var b=[],c=0;c<a.length;c++)a.hasOwnProperty(c)&&(b[c]=Sa(a[c]));return new w(b)}if(Pa(a)){var d=
new La,e;for(e in a)a.hasOwnProperty(e)&&d.set(e,Sa(a[e]));return d}if("function"===typeof a)return new x("",function(b){for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;d++)c[d]=Ra(this.evaluate(c[d]));return Sa(a.apply(a,c))});var g=typeof a;if(null===a||"string"===g||"number"===g||"boolean"===g)return a};var Ta={control:function(a,b){return new v(a,this.evaluate(b))},fn:function(a,b,c){var d=this.F(),e=this.evaluate(b);if(!(e instanceof w))throw"Error: non-List value given for Fn argument names.";var g=Array.prototype.slice.call(arguments,2);this.K().U(a.length+g.length);return new x(a,function(){return function(a){for(var b=new pa(d.N,d.I,d),c=Array.prototype.slice.call(arguments,0),h=0;h<c.length;h++)if(c[h]=this.evaluate(c[h]),c[h]instanceof v)return c[h];for(var n=e.get("length"),p=0;p<n;p++)p<
c.length?b.set(e.get(p),c[p]):b.set(e.get(p),void 0);b.set("arguments",new w(c));var q=Ka(b,g);if(q instanceof v)return"return"===q.C?q.getData():q}}())},list:function(a){var b=this.K();b.U(arguments.length);for(var c=new w,d=0;d<arguments.length;d++){var e=this.evaluate(arguments[d]);"string"===typeof e&&b.U(e.length?e.length-1:0);c.push(e)}return c},map:function(a){for(var b=this.K(),c=new La,d=0;d<arguments.length-1;d+=2){var e=this.evaluate(arguments[d])+"",g=this.evaluate(arguments[d+1]),h=e.length;
h+="string"===typeof g?g.length:1;b.U(h);c.set(e,g)}return c},undefined:function(){}};var Ua=function(){this.N=oa();this.I=na();this.za=new pa(this.N,this.I)};f=Ua.prototype;f.T=function(a,b){var c=new x(a,b);c.M();this.za.set(a,c)};f.Wb=function(a,b){Ta.hasOwnProperty(a)&&this.T(b||a,Ta[a])};f.K=function(){return this.N};f.Za=function(){this.N=oa();this.za.N=this.N};f.Ge=function(){this.I=na();this.za.I=this.I};f.L=function(a,b){var c=Array.prototype.slice.call(arguments,0);return this.zb(c)};
f.zb=function(a){for(var b,c=0;c<arguments.length;c++){var d=Ja(this.za,arguments[c]);b=d instanceof v||d instanceof x||d instanceof w||d instanceof La||null===d||void 0===d||"string"===typeof d||"number"===typeof d||"boolean"===typeof d?d:void 0}return b};f.M=function(){this.za.M()};Ua.prototype.makeImmutable=Ua.prototype.M;Ua.prototype.run=Ua.prototype.zb;Ua.prototype.execute=Ua.prototype.L;Ua.prototype.resetPermissions=Ua.prototype.Ge;Ua.prototype.resetQuota=Ua.prototype.Za;
Ua.prototype.getQuota=Ua.prototype.K;Ua.prototype.addNativeInstruction=Ua.prototype.Wb;Ua.prototype.addInstruction=Ua.prototype.T;var Va=function(a){for(var b=[],c=0;c<a.length();c++)a.has(c)&&(b[c]=a.get(c));return b};var Wa={Ne:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" "),concat:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));for(d=1;d<arguments.length;d++)if(arguments[d]instanceof w)for(var e=arguments[d],g=0;g<e.length();g++)c.push(e.get(g));else c.push(arguments[d]);return new w(c)},every:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&
!b.o(a,this.get(d),d,this))return!1;return!0},filter:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&b.o(a,this.get(e),e,this)&&d.push(this.get(e));return new w(d)},forEach:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)this.has(d)&&b.o(a,this.get(d),d,this)},hasOwnProperty:function(a,b){return this.has(b)},indexOf:function(a,b,c){var d=this.length(),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var g=e;g<d;g++)if(this.has(g)&&this.get(g)===
b)return g;return-1},join:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));return c.join(b)},lastIndexOf:function(a,b,c){var d=this.length(),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var g=e;0<=g;g--)if(this.has(g)&&this.get(g)===b)return g;return-1},map:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&(d[e]=b.o(a,this.get(e),e,this));return new w(d)},pop:function(){return this.pop()},push:function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,
1))},reduce:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=0;else{if(0==d)throw"TypeError: Reduce on List with no elements.";for(var h=0;h<d;h++)if(this.has(h)){e=this.get(h);g=h+1;break}if(h==d)throw"TypeError: Reduce on List with no elements.";}for(h=g;h<d;h++)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reduceRight:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=d-1;else{if(0==d)throw"TypeError: ReduceRight on List with no elements.";for(var h=1;h<=d;h++)if(this.has(d-
h)){e=this.get(d-h);g=d-(h+1);break}if(h>d)throw"TypeError: ReduceRight on List with no elements.";}for(h=g;0<=h;h--)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reverse:function(){for(var a=Va(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this},shift:function(){return this.shift()},slice:function(a,b,c){var d=this.length();void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,
c);for(var e=[],g=b;g<c;g++)e.push(this.get(g));return new w(e)},some:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&b.o(a,this.get(d),d,this))return!0;return!1},sort:function(a,b){var c=Va(this);void 0===b?c.sort():c.sort(function(c,d){return Number(b.o(a,c,d))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)},splice:function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,1,arguments.length-1))},toString:function(){return this.toString()},
unshift:function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))}};var y={qc:{ADD:0,AND:1,APPLY:2,ASSIGN:3,BREAK:4,CASE:5,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,
PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42}},Xa="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),Ya=new v("break"),Za=new v("continue");y.add=function(a,b){return this.evaluate(a)+this.evaluate(b)};y.and=function(a,b){return this.evaluate(a)&&this.evaluate(b)};
y.apply=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof w))throw"Error: Non-List argument given to Apply instruction.";if(null===a||void 0===a)throw"TypeError: Can't read property "+b+" of "+a+".";if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw"TypeError: "+a+"."+b+" is not a function.";}if("string"==typeof a){if(0<=va(Xa,b))return Sa(a[b].apply(a,Va(c)));throw"TypeError: "+b+" is not a function";}if(a instanceof w){if(a.has(b)){var d=
a.get(b);if(d instanceof x){var e=Va(c);e.unshift(this.F());return d.o.apply(d,e)}throw"TypeError: "+b+" is not a function";}if(0<=va(Wa.Ne,b))return e=Va(c),e.unshift(this.F()),Wa[b].apply(a,e)}if(a instanceof x||a instanceof La){if(a.has(b)){d=a.get(b);if(d instanceof x)return e=Va(c),e.unshift(this.F()),d.o.apply(d,e);throw"TypeError: "+b+" is not a function";}if("toString"==b)return a instanceof x?a.getName():a.toString();if("hasOwnProperty"==b)return a.has.apply(a,Va(c))}throw"TypeError: Object has no '"+
b+"' property.";};y.assign=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw"Invalid key name given for assignment.";var c=this.F();if(!c.has(a))throw"Attempting to assign to undefined value "+b;var d=this.evaluate(b);c.set(a,d);return d};y["break"]=function(){return Ya};y["case"]=function(a){for(var b=this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof v)return d}};y["continue"]=function(){return Za};
y.zd=function(a,b,c){var d=new w;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var g=[y.qc.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.F().set(a,this.evaluate(g))};y.Cd=function(a,b){return this.evaluate(a)/this.evaluate(b)};y.Fd=function(a,b){return this.evaluate(a)==this.evaluate(b)};y.Gd=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
y.Jd=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.F();if("string"==typeof b)for(var e=0;e<b.length;e++){d.set(a,e);var g=this.xa(c);if(g instanceof v){if("break"==g.C)break;if("return"==g.C)return g}}else if(b instanceof La||b instanceof w||b instanceof x){var h=b.V(),k=h.length();for(e=0;e<k;e++)if(d.set(a,h.get(e)),g=this.xa(c),g instanceof v){if("break"==g.C)break;if("return"==g.C)return g}}};y.get=function(a){return this.F().get(this.evaluate(a))};
y.ic=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw"TypeError: cannot access property of "+a+".";a instanceof La||a instanceof w||a instanceof x?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ka(b)&&(c=a[b]));return c};y.Nd=function(a,b){return this.evaluate(a)>this.evaluate(b)};y.Od=function(a,b){return this.evaluate(a)>=this.evaluate(b)};y.Vd=function(a,b){return this.evaluate(a)===this.evaluate(b)};y.Wd=function(a,b){return this.evaluate(a)!==this.evaluate(b)};
y["if"]=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.xa(d);if(e instanceof v)return e};y.de=function(a,b){return this.evaluate(a)<this.evaluate(b)};y.ee=function(a,b){return this.evaluate(a)<=this.evaluate(b)};y.he=function(a,b){return this.evaluate(a)%this.evaluate(b)};y.multiply=function(a,b){return this.evaluate(a)*this.evaluate(b)};y.ie=function(a){return-this.evaluate(a)};y.je=function(a){return!this.evaluate(a)};
y.ke=function(a,b){return this.evaluate(a)!=this.evaluate(b)};y["null"]=function(){return null};y.or=function(a,b){return this.evaluate(a)||this.evaluate(b)};y.Ec=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c};y.Fc=function(a){return this.evaluate(a)};y.quote=function(a){return Array.prototype.slice.apply(arguments)};y["return"]=function(a){return new v("return",this.evaluate(a))};
y.setProperty=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw"TypeError: Can't set property "+b+" of "+a+".";(a instanceof x||a instanceof w||a instanceof La)&&a.set(b,c);return c};y.Me=function(a,b){return this.evaluate(a)-this.evaluate(b)};
y["switch"]=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!ua(b)||!ua(c))throw"Error: Malformed switch instruction.";for(var d,e=!1,g=0;g<b.length;g++)if(e||a===this.evaluate(b[g]))if(d=this.evaluate(c[g]),d instanceof v){var h=d.C;if("break"==h)return;if("return"==h||"continue"==h)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof v&&("return"==d.C||"continue"==d.C)))return d};
y.Oe=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)};y["typeof"]=function(a){a=this.evaluate(a);return a instanceof x?"function":typeof a};y.undefined=function(){};y["var"]=function(a){for(var b=this.F(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}};
y["while"]=function(a,b,c,d){var e,g=this.evaluate(d);if(this.evaluate(c)&&(e=this.xa(g),e instanceof v)){if("break"==e.C)return;if("return"==e.C)return e}for(;this.evaluate(a);){e=this.xa(g);if(e instanceof v){if("break"==e.C)break;if("return"==e.C)return e}this.evaluate(b)}};var cb=function(){this.oc=!1;this.H=new Ua;$a(this);this.oc=!0};cb.prototype.ae=function(){return this.oc};cb.prototype.isInitialized=cb.prototype.ae;cb.prototype.L=function(a){this.H.I.yc(String(a[0]))||(this.H.I.reset(),this.H.I.Ic(!0));return this.H.zb(a)};cb.prototype.execute=cb.prototype.L;cb.prototype.M=function(){this.H.M()};cb.prototype.makeImmutable=cb.prototype.M;
var $a=function(a){function b(a,b){e.H.Wb(a,String(b))}function c(a,b){e.H.T(String(d[a]),b)}var d=y.qc,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",y.add);c("AND",y.and);c("APPLY",y.apply);c("ASSIGN",y.assign);c("BREAK",y["break"]);c("CASE",y["case"]);c("CONTINUE",y["continue"]);c("DEFAULT",y["case"]);c("DEFN",y.zd);c("DIVIDE",y.Cd);c("EQUALS",y.Fd);c("EXPRESSION_LIST",y.Gd);c("FOR_IN",y.Jd);c("GET",y.get);c("GET_INDEX",
y.ic);c("GET_PROPERTY",y.ic);c("GREATER_THAN",y.Nd);c("GREATER_THAN_EQUALS",y.Od);c("IDENTITY_EQUALS",y.Vd);c("IDENTITY_NOT_EQUALS",y.Wd);c("IF",y["if"]);c("LESS_THAN",y.de);c("LESS_THAN_EQUALS",y.ee);c("MODULUS",y.he);c("MULTIPLY",y.multiply);c("NEGATE",y.ie);c("NOT",y.je);c("NOT_EQUALS",y.ke);c("NULL",y["null"]);c("OR",y.or);c("POST_DECREMENT",y.Ec);c("POST_INCREMENT",y.Ec);c("PRE_DECREMENT",y.Fc);c("PRE_INCREMENT",y.Fc);c("QUOTE",y.quote);c("RETURN",y["return"]);c("SET_PROPERTY",y.setProperty);
c("SUBTRACT",y.Me);c("SWITCH",y["switch"]);c("TERNARY",y.Oe);c("TYPEOF",y["typeof"]);c("VAR",y["var"]);c("WHILE",y["while"])};cb.prototype.T=function(a,b){this.H.T(a,b)};cb.prototype.addInstruction=cb.prototype.T;cb.prototype.K=function(){return this.H.K()};cb.prototype.getQuota=cb.prototype.K;cb.prototype.Za=function(){this.H.Za()};cb.prototype.resetQuota=cb.prototype.Za;cb.prototype.oa=function(a){this.H.I.oa(a)};cb.prototype.Pa=function(a,b,c){this.H.I.Xb(a,b,c)};var db=function(){this.Va={}};db.prototype.get=function(a){return this.Va.hasOwnProperty(a)?this.Va[a]:void 0};db.prototype.add=function(a,b){if(this.Va.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";if(!b)throw"Attempting to add an undefined function: "+a+".";var c=new x(a,function(){for(var a=Array.prototype.slice.call(arguments,0),c=0;c<a.length;c++)a[c]=this.evaluate(a[c]);return b.apply(this,a)});c.M();this.Va[a]=c};
db.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var z=window,B=document,eb=navigator,fb=B.currentScript&&B.currentScript.src,gb=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},hb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},ib=function(a,b,c){var d=B.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;hb(d,b);c&&(d.onerror=c);ha()&&d.setAttribute("nonce",ha());var e=B.getElementsByTagName("script")[0]||B.body||B.head;
e.parentNode.insertBefore(d,e);return d},jb=function(a,b){var c=B.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=B.body&&B.body.lastChild||B.body||B.head;d.parentNode.insertBefore(c,d);hb(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},kb=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&
a.attachEvent("on"+b,c)},lb=function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},I=function(a){z.setTimeout(a,0)},nb=function(a){var b=B.getElementById(a);if(b&&mb(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(mb(document.all[a][c],"id")==a)return document.all[a][c];return b},mb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},ob=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,
""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},qb=function(a){var b=B.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},rb=function(a){eb.sendBeacon&&eb.sendBeacon(a)||G(a)};var sb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var tb=/:[0-9]+$/,ub=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")==b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},vb=function(a,b,c,d,e){var g,h=function(a){return a?a.replace(":","").toLowerCase():""},k=h(a.protocol)||h(z.location.protocol);b&&(b=String(b).toLowerCase());switch(b){case "protocol":g=k;break;case "host":g=(a.hostname||z.location.hostname).replace(tb,"").toLowerCase();
if(c){var l=/^www\d*\./.exec(g);l&&l[0]&&(g=g.substr(l[0].length))}break;case "port":g=String(Number(a.hostname?a.port:z.location.port)||("http"==k?80:"https"==k?443:""));break;case "path":g="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var m=g.split("/");0<=va(d||[],m[m.length-1])&&(m[m.length-1]="");g=m.join("/");break;case "query":g=a.search.replace("?","");e&&(g=ub(g,e));break;case "extension":var n=a.pathname.split(".");g=1<n.length?n[n.length-1]:"";g=g.split("/")[0];break;case "fragment":g=
a.hash.replace("#","");break;default:g=a&&a.href}return g},wb=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},N=function(a){var b=document.createElement("a");a&&(sb.test(a),b.href=a);var c=b.pathname;"/"!==c[0]&&(c="/"+c);var d=b.hostname.replace(tb,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var zb=function(){this.Ya=new cb;var a=new db;a.addAll(xb());yb(this,function(b){return a.get(b)})},xb=function(){return{callInWindow:Ab,callLater:Bb,copyFromWindow:Cb,encodeURI:encodeURI,encodeURIComponent:encodeURIComponent,getReferrer:Db,getUrl:Eb,getUrlFragment:Fb,isPlainObject:Gb,injectHiddenIframe:Hb,injectScript:Ib,logToConsole:Jb,queryPermission:Kb,removeUrlFragment:Lb,replaceAll:Mb,sendPixel:Nb,setInWindow:Ob}};zb.prototype.L=function(a){return this.Ya.L(a)};zb.prototype.execute=zb.prototype.L;
var yb=function(a,b){a.Ya.T("require",b)};zb.prototype.oa=function(a){this.Ya.oa(a)};zb.prototype.Pa=function(a,b,c){this.Ya.Pa(a,b,c)};function Ab(a,b){for(var c=a.split("."),d=z,e=d[c[0]],g=1;e&&g<c.length;g++)d=e,e=e[c[g]];if("function"==Na(e)){var h=[];for(g=1;g<arguments.length;g++)h.push(Ra(arguments[g]));e.apply(d,h)}}function Bb(a){var b=this.F();I(function(){a instanceof x&&a.o(b)})}
function Cb(a,b,c){for(var d=a.split("."),e=z,g=0;g<d.length-1;g++)if(e=e[d[g]],void 0===e||null===e)return;b&&(void 0===e[d[g]]||c&&!e[d[g]])&&(e[d[g]]=Ra(b));return Sa(e[d[g]])}function Db(){return B.referrer}function Eb(a,b,c,d){var e=z.location.href,g;if(c&&c instanceof w){g=[];for(var h=0;h<c.length();h++){var k=c.get(h);"string"==typeof k&&g.push(k)}}return vb(N(e),a,b,g,d)}function Fb(a){return vb(N(a),"fragment")}function Gb(a){return a instanceof La}
function Hb(a,b){var c=this.F();jb(a,function(){b instanceof x&&b.o(c)})}var Pb={};
function Ib(a,b,c,d){this.ya().assert("injectScript",a);var e=this.F(),g=function(){b instanceof x&&b.o(e)},h=function(){c instanceof x&&c.o(e)};d?Pb[d]?(Pb[d].onSuccess.push(g),Pb[d].onFailure.push(h)):(Pb[d]={onSuccess:[g],onFailure:[h]},g=function(){for(var a=Pb[d].onSuccess,b=0;b<a.length;b++)I(a[b]);a.push=function(a){I(a);return 0}},h=function(){for(var a=Pb[d].onFailure,b=0;b<a.length;b++)I(a[b]);Pb[d]=null},ib(a,g,h)):ib(a,g,h)}
function Jb(){try{this.ya().assert("logging")}catch(c){return}for(var a=Array.prototype.slice.call(arguments,0),b=0;b<a.length;b++)a[b]=Ra(a[b]);console.log.apply(console,a)}function Lb(a){return wb(N(a))}function Mb(a,b,c){return a.replace(new RegExp(b,"g"),c)}function Nb(a,b,c){this.ya().assert("sendPixel",a);var d=this.F();G(a,function(){b instanceof x&&b.o(d)},function(){c instanceof x&&c.o(d)})}
function Ob(a,b,c){this.ya().assert("writeGlobals",a);for(var d=a.split("."),e=z,g=0;g<d.length-1;g++)if(e=e[d[g]],void 0===e)return!1;return void 0===e[d[g]]||c?(e[d[g]]=Ra(b),!0):!1}function Kb(a,b){try{return this.ya().assert.apply(null,Array.prototype.slice.call(arguments,0)),!0}catch(c){return!1}};var mc,nc=[],oc=[],pc=[],qc=[],rc=[],sc={},tc,uc,vc,wc=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},xc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=!!sc[b],d={},e;for(e in a)a.hasOwnProperty(e)&&0===e.indexOf("vtp_")&&(d[c?e:e.substr(4)]=a[e]);return c?sc[b](d):mc(b,d)},zc=function(a,b,c,d){c=c||[];d=d||qa;var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=yc(a[g],b,c,d));return e},
Ac=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=sc[b];return c?c.b||0:0},yc=function(a,b,c,d){if(ua(a)){var e;switch(a[0]){case "function_id":return a[1];case "list":e=[];for(var g=1;g<a.length;g++)e.push(yc(a[g],b,c,d));return e;case "macro":var h=a[1];if(c[h])return;var k=nc[h];if(!k||b(k))return;c[h]=!0;try{var l=zc(k,b,c,d);e=xc(l);vc&&(e=vc.ud(e,l))}catch(C){d(h,C),e=!1}c[h]=!1;return e;case "map":e={};for(var m=1;m<a.length;m+=2)e[yc(a[m],
b,c,d)]=yc(a[m+1],b,c,d);return e;case "template":e=[];for(var n=!1,p=1;p<a.length;p++){var q=yc(a[p],b,c,d);uc&&(n=n||q===uc.Ja);e.push(q)}return uc&&n?uc.vd(e):e.join("");case "escape":e=yc(a[1],b,c,d);if(uc&&ua(a[1])&&"macro"===a[1][0]&&uc.be(a))return uc.ue(e);e=String(e);for(var r=2;r<a.length;r++)Qb[a[r]]&&(e=Qb[a[r]](e));return e;case "tag":var u=a[1];if(!qc[u])throw Error("Unable to resolve tag reference "+u+".");return e={cc:a[2],index:u};case "zb":var t={arg0:a[2],arg1:a[3],ignore_case:a[5]};
t["function"]=a[1];var A=Dc(t,b,c,d);a[4]&&(A=!A);return A;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Dc=function(a,b,c,d){try{return tc(zc(a,b,c,d))}catch(e){JSON.stringify(a)}return null};var Ec=null,Ic=function(a){function b(a){for(var b=0;b<a.length;b++)d[a[b]]=!0}var c=[],d=[];Ec=Fc(a,Gc()||function(){});for(var e=0;e<oc.length;e++){var g=oc[e],h=Hc(g);if(h){for(var k=g.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(g.block||[])}else null===h&&b(g.block||[])}var m=[];for(e=0;e<qc.length;e++)c[e]&&!d[e]&&(m[e]=!0);return m},Hc=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Ec(b[c]);if(!d)return null===d?null:!1}var e=a.unless||[];for(c=0;c<e.length;c++){d=Ec(e[c]);if(null===
d)return null;if(d)return!1}return!0};var Fc=function(a,b){var c=[];return function(d){void 0===c[d]&&(c[d]=Dc(pc[d],a,void 0,b));return c[d]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Lc={},Mc=null;Lc.w="UA-2577926-1";Lc.Na="af";var Nc=null,Oc=null,Pc="//www.googletagmanager.com/a?id="+Lc.w+"&cv=1",Qc={},Rc={},Sc=function(){var a=Mc.sequence||0;Mc.sequence=a+1;return a};var P=function(){var a=function(a){return{toString:function(){return a}}};return{Lb:a("convert_case_to"),Mb:a("convert_false_to"),Nb:a("convert_null_to"),Ob:a("convert_true_to"),Pb:a("convert_undefined_to"),ca:a("function"),Mc:a("instance_name"),Nc:a("live_only"),Oc:a("malware_disabled"),Pc:a("once_per_event"),Rb:a("once_per_load"),Sb:a("setup_tags"),Qc:a("tag_id"),Tb:a("teardown_tags")}}();var Tc=new Ea,Uc={},Xc={set:function(a,b){Qa(Vc(a,b),Uc)},get:function(a){return Wc(a,2)},reset:function(){Tc=new Ea;Uc={}}},Wc=function(a,b){return 2!=b?Tc.get(a):Yc(a)},Yc=function(a,b,c){var d=a.split(".");var e=function(a,b){for(var c=0;void 0!==a&&c<d.length;c++){if(null===a)return!1;a=a[d[c]]}return void 0!==a||1<c?a:b.length?e(Zc(b.pop()),b):$c(d)};return e(Uc.eventModel,[b,c]);return $c(d)},$c=function(a){for(var b=Uc,c=0;c<a.length;c++){if(null===
b)return!1;if(void 0===b)break;b=b[a[c]]}return b};var Zc=function(a){if(a){var b=$c(["gtag","targets",a]);return Pa(b)?b:void 0}},ad=function(a,b){function c(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(d[b]=null)}var d={};c(Uc);delete d.eventModel;c(Zc(a));c(Zc(b));c(Uc.eventModel);var e=[],g;for(g in d)d.hasOwnProperty(g)&&e.push(g);return e};
var bd=function(a,b){Tc.set(a,b);Qa(Vc(a,b),Uc)},Vc=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c};var cd=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),dd={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},ed={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},fd=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var gd=function(a){var b=Wc("gtm.whitelist");b=["google","gtagfl","oid","op"];var c=b&&fd(Ba(b),dd),d=Wc("gtm.blacklist")||Wc("tagTypeBlacklist")||[];
cd.test(z.location&&z.location.hostname)&&(d=Ba(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&fd(Ba(d),ed),g={};return function(h){var k=h&&h[P.ca];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];var l=Rc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>va(c,k))if(l&&0<l.length)for(var p=0;p<l.length;p++){if(0>va(c,l[p])){n=!1;break a}}else{n=!1;break a}n=!0}m=n}var q=!1;if(d){var r;if(!(r=
0<=va(e,k)))a:{for(var u=l||[],t=new Ea,A=0;A<e.length;A++)t.set(e[A],!0);for(var C=0;C<u.length;C++)if(t.get(u[C])){r=!0;break a}r=!1}q=r}return g[k]=!m||q}};var hd={ud:function(a,b){b[P.Lb]&&"string"===typeof a&&(a=1==b[P.Lb]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(P.Nb)&&null===a&&(a=b[P.Nb]);b.hasOwnProperty(P.Pb)&&void 0===a&&(a=b[P.Pb]);b.hasOwnProperty(P.Ob)&&!0===a&&(a=b[P.Ob]);b.hasOwnProperty(P.Mb)&&!1===a&&(a=b[P.Mb]);return a}};var id=function(a,b){this.qe=b};ia(id,Error);id.prototype.getParameters=function(){return this.qe};var jd=function(a){var b=Mc.zones;!b&&a&&(b=Mc.zones=a());return b},kd={active:!0,isWhitelisted:function(){return!0}};var ld=!1,md=0,nd=[];function od(a){if(!ld){var b=B.createEventObject,c="complete"==B.readyState,d="interactive"==B.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ld=!0;for(var e=0;e<nd.length;e++)I(nd[e])}nd.push=function(){for(var a=0;a<arguments.length;a++)I(arguments[a]);return 0}}}function pd(){if(!ld&&140>md){md++;try{B.documentElement.doScroll("left"),od()}catch(a){z.setTimeout(pd,50)}}}var qd=function(a){ld?a():nd.push(a)};var rd=function(){function a(a){return!ta(a)||0>a?0:a}if(!Mc._li&&z.performance&&z.performance.timing){var b=z.performance.timing.navigationStart,c=ta(Xc.get("gtm.start"))?Xc.get("gtm.start"):0;Mc._li={cst:a(c-b),cbt:a(Nc-b)}}};var sd=!1,td=function(){return z.GoogleAnalyticsObject&&z[z.GoogleAnalyticsObject]};var ud=function(a){z.GoogleAnalyticsObject||(z.GoogleAnalyticsObject=a||"ga");var b=z.GoogleAnalyticsObject;if(!z[b]){var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);z[b]=c}rd();return z[b]},wd=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=td();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var Ad=function(){return"&tc="+qc.filter(function(a){return a}).length},Bd="0.005000">Math.random(),Cd=function(){var a=0,b=0;return{ce:function(){if(2>a)return!1;1E3<=Da()-b&&(a=0);return 2<=a},Be:function(){1E3<=Da()-b&&(a=0);a++;b=Da()}}},Dd="",Ed=function(){Dd=[Pc,"&v=3&t=t","&pid="+wa(),"&rv="+Lc.Na].join("")},Fd={},Gd="",Hd=void 0,Id={},Jd={},Kd=void 0,Ld=null,Md=1E3,Nd=function(){var a=Hd;return void 0===a?"":[Dd,Fd[a]?"":"&es=1",Id[a],Ad(),Gd,"&z=0"].join("")},Od=function(){Kd&&
(z.clearTimeout(Kd),Kd=void 0);void 0===Hd||Fd[Hd]&&!Gd||(Jd[Hd]||Ld.ce()||0>=Md--?Jd[Hd]=!0:(Ld.Be(),G(Nd()),Fd[Hd]=!0,Gd=""))},Pd=function(a,b,c){if(Bd&&!Jd[a]&&b){a!==Hd&&(Od(),Hd=a);var d=c+String(b[P.ca]||"").replace(/_/g,"");Gd=Gd?Gd+"."+d:"&tr="+d;Kd||(Kd=z.setTimeout(Od,500));2022<=Nd().length&&Od()}};function Qd(a,b,c,d,e,g){var h=qc[a],k=Rd(a,b,c,d,e,g);if(!k)return null;var l=yc(h[P.Sb],g.X,[],Sd());if(l&&l.length){var m=l[0];k=Qd(m.index,b,k,1===m.cc?e:k,e,g)}return k}
function Rd(a,b,c,d,e,g){function h(){var b=zc(k,g.X,[],l);b.vtp_gtmOnSuccess=function(){Pd(g.id,qc[a],"5");c()};b.vtp_gtmOnFailure=function(){Pd(g.id,qc[a],"6");d()};b.vtp_gtmTagId=k.tag_id;if(k[P.Oc])d();else{Pd(g.id,k,"1");try{xc(b)}catch(C){Pd(g.id,
k,"7");e()}}}var k=qc[a];if(g.X(k))return null;var l=Sd(),m=yc(k[P.Tb],g.X,[],l);if(m&&m.length){var n=m[0],p=Qd(n.index,b,c,d,e,g);if(!p)return null;c=p;d=2===n.cc?e:p}if(k[P.Rb]||k[P.Pc]){var q=k[P.Rb]?rc:b,r=c,u=d;if(!q[a]){h=Ga(h);var t=Td(a,q,h);c=t.S;d=t.la}return function(){q[a](r,u)}}return h}
function Td(a,b,c){var d=[],e=[];b[a]=Ud(d,e,c);return{S:function(){b[a]=Vd;for(var c=0;c<d.length;c++)d[c]()},la:function(){b[a]=Wd;for(var c=0;c<e.length;c++)e[c]()}}}function Ud(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function Vd(a){a()}function Wd(a,b){b()}function Sd(){return function(){}};function Xd(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ga(function(){b++;d&&b>=c&&a()})},bd:function(){d=!0;b>=c&&a()}}}function Yd(a,b){var c,d=b.b,e=a.b;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.Kc,k=b.Kc;g=h>k?1:h<k?-1:0}return g}
function Zd(a,b){if(!Bd)return;var c=function(a){var d=b.X(qc[a])?"3":"4",g=yc(qc[a][P.Sb],b.X,[],qa);g&&g.length&&c(g[0].index);Pd(b.id,qc[a],d);var h=yc(qc[a][P.Tb],b.X,[],qa);h&&h.length&&c(h[0].index)};c(a);}var $d=!1;function Gc(){return function(){}};var ae=function(a,b){var c=wc(a,b),d;for(d in void 0)(void 0).hasOwnProperty(d)&&(c[d]=(void 0)[d]);qc.push(c);return qc.length-1};var be="allow_ad_personalization_signals cookie_domain cookie_expires cookie_name cookie_path custom_params event_callback event_timeout groups send_to send_page_view session_duration user_properties".split(" ");var ce=/[A-Z]+/,de=/\s/,ee=function(a){if(sa(a)&&(a=a.trim(),!de.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(ce.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],W:d}}}}};var fe=null,ge={},he={},ie;function je(){fe=fe||!Mc.gtagRegistered;Mc.gtagRegistered=!0;return fe}var ke=function(a,b){var c={event:a};b&&(c.eventModel=Qa(b),b.event_callback&&(c.eventCallback=b.event_callback),b.event_timeout&&(c.eventTimeout=b.event_timeout));return c};
function le(a){if(void 0===he[a.id]){var b;switch(a.prefix){case "UA":b=ae("gtagua",{trackingId:a.id});break;case "AW":b=ae("gtagaw",{conversionId:a});break;case "DC":b=ae("gtagfl",{targetId:a.id});break;case "GF":b=ae("gtaggf",{conversionId:a});break;case "G":b=ae("get",{trackingId:a.id,isAutoTag:!0});break;case "HA":b=ae("gtagha",{conversionId:a});break;default:return}if(!ie){var c=wc("v",{name:"send_to",dataLayerVersion:2});nc.push(c);ie=["macro",nc.length-1]}var d={arg0:ie,arg1:a.id,ignore_case:!1};
d[P.ca]="_lc";pc.push(d);var e={"if":[pc.length-1],add:[b]};e["if"]&&(e.add||e.block)&&oc.push(e);he[a.id]=b}}
var ne={event:function(a){var b=a[1];if(sa(b)&&!(3<a.length)){var c;if(2<a.length){if(!Pa(a[2]))return;c=a[2]}var d=ke(b,c);var e;var g=c,h=Wc("gtag.fields.send_to",2);sa(h)||(h="send_to");var k=g&&g[h];void 0===k&&(k=Wc(h,2),void 0===k&&(k="default"));if(sa(k)||ua(k)){for(var l,m=k.toString().replace(/\s+/g,"").split(","),n=[],p=0;p<m.length;p++)0<=m[p].indexOf("-")?n.push(m[p]):n=n.concat(ge[m[p]]||[]);l=n;for(var q={},r=0;r<l.length;++r){var u=ee(l[r]);u&&(q[u.id]=
u)}var t=[],A;for(A in q)if(q.hasOwnProperty(A)){var C=q[A];"AW"===C.prefix&&C.W[1]&&t.push(C.containerId)}for(var D=0;D<t.length;++D)delete q[t[D]];var L=[],E;for(E in q)q.hasOwnProperty(E)&&L.push(q[E]);e=L}else e=void 0;if(!e)return;var F=je();F||me();for(var J=[],H=0;F&&H<e.length;H++){var K=e[H];J.push(K.id);le(K)}d.eventModel=d.eventModel||{};0<e.length?d.eventModel.send_to=J.join():delete d.eventModel.send_to;return d}},set:function(a){var b;2==a.length&&Pa(a[1])?
b=Qa(a[1]):3==a.length&&sa(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=Qa(b),b.event="gtag.set",b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},config:function(a){var b=a[2]||{};if(2>a.length||!sa(a[1])||!Pa(b))return;var c=ee(a[1]);if(!c)return;je()?le(c):me();var d=c.id,e;for(e in ge)if(ge.hasOwnProperty(e)){var g=va(ge[e],d);0<=g&&ge[e].splice(g,1)}var h=c.id,k=b.groups||"default";k=k.toString().split(",");
for(var l=0;l<k.length;l++)ge[k[l]]=ge[k[l]]||[],ge[k[l]].push(h);delete b.groups;bd("gtag.targets."+c.id,void 0);bd("gtag.targets."+c.id,Qa(b));var m={};m.send_to=c.id;return ke("gtag.config",m);}},me=Ga(function(){});var oe=!1,pe=[];function qe(){if(!oe){oe=!0;for(var a=0;a<pe.length;a++)I(pe[a])}};var re=[],se=!1,te=function(a){var b=a.eventCallback,c=Ga(function(){ra(b)&&I(function(){b(Lc.w)})}),d=a.eventTimeout;d&&z.setTimeout(c,Number(d));return c},ue=function(){for(var a=!1;!se&&0<re.length;){se=!0;delete Uc.eventModel;var b=re.shift();if(ra(b))try{b.call(Xc)}catch(Ie){}else if(ua(b)){var c=b;if(sa(c[0])){var d=c[0].split("."),e=d.pop(),g=c.slice(1),h=Wc(d.join("."),2);if(void 0!==h&&null!==h)try{h[e].apply(h,g)}catch(Ie){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{if(b.length&&sa(b[0])){var l=ne[b[0]];if(l){b=l(b);break a}}b=void 0}if(!b){se=!1;continue}}var m;var n=void 0,p=b,q=p._clear;for(n in p)p.hasOwnProperty(n)&&"_clear"!==n&&(q&&bd(n,void 0),bd(n,p[n]));var r=p.event;if(r){var u=p["gtm.uniqueEventId"];u||(u=Sc(),p["gtm.uniqueEventId"]=u,bd("gtm.uniqueEventId",u));Oc=r;var t;var A,C,D=p,L=D.event,E=D["gtm.uniqueEventId"],F=Mc.zones;C=F?F.checkState(Lc.w,E):kd;if(C.active){var J=te(D);c:{var H=C.isWhitelisted;
if("gtm.js"==L){if($d){A=!1;break c}$d=!0}var K=E,R=L;if(Bd&&!Jd[K]&&Hd!==K){Od();Hd=K;Gd="";var ja=Id,W=K,ba,M=R;ba=0===M.indexOf("gtm.")?encodeURIComponent(M):"*";ja[W]="&e="+ba+"&eid="+K;Kd||(Kd=z.setTimeout(Od,500))}var T=gd(H),O={id:E,name:L,callback:J||qa,X:T,Ea:[]};O.Ea=Ic(T);for(var za,ab=O,Vb=Xd(ab.callback),Bc=[],pb=[],bb=0;bb<qc.length;bb++)if(ab.Ea[bb]){var Je=qc[bb];var Wb=Vb.add();try{var Ke=Qd(bb,Bc,Wb,Wb,Wb,ab);Ke?pb.push({Kc:bb,b:Ac(Je),L:Ke}):(Zd(bb,ab),Wb())}catch(Ie){Wb()}}Vb.bd();pb.sort(Yd);for(var vd=0;vd<pb.length;vd++)pb[vd].L();za=0<pb.length;if("gtm.js"===L||"gtm.sync"===L)d:{}if(za){for(var Mg={__cl:!0,__evl:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Cc=0;Cc<O.Ea.length;Cc++)if(O.Ea[Cc]){var Me=qc[Cc];if(Me&&!Mg[Me[P.ca]]){A=!0;break c}}A=!1}else A=za}t=A?!0:!1}else t=!1;Oc=null;m=t}else m=!1;a=m||a}se=!1}return!a},ve=function(){var a=ue();try{var b=z["dataLayer"].hide;if(b&&void 0!==b[Lc.w]&&b.end){b[Lc.w]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&
!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},we=function(){var a=gb("dataLayer",[]),b=gb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};nd.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});pe.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(re.push.apply(re,b);300<this.length;)this.shift();return ue()};re.push.apply(re,a.slice(0));
I(ve)};var xe={};xe.Ja=new String("undefined");xe.fb={};var ye=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===xe.Ja?b:a[d]);return c.join("")}};ye.prototype.toString=function(){return this.resolve("undefined")};ye.prototype.valueOf=ye.prototype.toString;xe.vd=function(a){return new ye(a)};var ze={};xe.Ce=function(a,b){var c=Sc();ze[c]=[a,b];return c};xe.Zb=function(a){var b=a?0:1;return function(a){var c=ze[a];if(c&&"function"===typeof c[b])c[b]();ze[a]=void 0}};
xe.be=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};xe.ue=function(a){if(a===xe.Ja)return a;var b=Sc();xe.fb[b]=a;return'google_tag_manager["'+Lc.w+'"].macro('+b+")"};xe.Rc=ye;var Ae=new Ea,Be=function(a,b){function c(a){var b=N(a),c=vb(b,"protocol"),d=vb(b,"host",!0),e=vb(b,"port"),g=vb(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===c||"http"==c&&"80"==e||"https"==c&&"443"==e)c="web",e="default";return[c,d,e,g]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0};
function Ce(a){var b=a.arg0,c=a.arg1;switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var d;a:{if(b){var e=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var g=0;g<e.length;g++)if(b[e[g]]){d=b[e[g]](c);break a}}catch(u){}}d=!1}return d;case "_ew":var h,k;h=String(b);k=String(c);var l=h.length-k.length;return 0<=l&&h.indexOf(k,l)==l;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);
case "_gt":return Number(b)>Number(c);case "_lc":var m;m=String(b).split(",");return 0<=va(m,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var n;var p=a.ignore_case?"i":void 0;try{var q=String(c)+p,r=Ae.get(q);r||(r=new RegExp(c,p),Ae.set(q,r));n=r.test(b)}catch(u){n=!1}return n;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Be(b,c)}return!1};var De=function(){return!1};function Ee(a,b){return Sa(Wc(a,b||2))}function Fe(){return(new Date).getTime()}function Ge(a){return ya(Ra(a))}function He(a){return null===a?"null":void 0===a?"undefined":a.toString()}function Ne(a,b){return wa(a,b)}function Oe(a,b,c){if(!(a instanceof w))return null;for(var d=new La,e=!1,g=0;g<a.length();g++){var h=a.get(g);h instanceof La&&h.has(b)&&h.has(c)&&(d.set(h.get(b),h.get(c)),e=!0)}return e?d:null}
var Pe=function(){var a=new db,b=xb();De()&&(b.loadJavaScript=qa,b.loadIframe=qa);a.addAll({injectScript:b.injectScript,sendPixel:b.sendPixel,injectHiddenIframe:b.injectHiddenIframe,encodeUri:b.encodeURI,encodeUriComponent:b.encodeURIComponent,setInWindow:b.setInWindow,copyFromWindow:b.copyFromWindow,copyFromDataLayer:Ee,getUrl:b.getUrl,getDate:Fe,callLater:b.callLater,generateRandom:Ne,makeTableMap:Oe,makeString:He,makeInteger:Ge,logToConsole:b.logToConsole,queryPermission:b.queryPermission});return function(b){return a.get(b)}};var Qe,Te=function(){var a=data.runtime||[],b=data.permissions||{};Qe=new zb;mc=function(a,b){var c=new La,d;for(d in b)b.hasOwnProperty(d)&&c.set(d,Sa(b[d]));var e=Qe.L([a,c]);e instanceof v&&"return"===e.C&&(e=e.getData());return Ra(e)};tc=Ce;yb(Qe,Pe());for(var c=0;c<a.length;c++){var d=a[c];if(!ua(d)||3>d.length){if(0==d.length)continue;return}Qe.L(d)}var e=function(a){throw Re(a,{},"The requested permission is not configured.");};Qe.oa(e);for(var g in b)if(b.hasOwnProperty(g)){var h=b[g],k=!1,
l;for(l in h)h.hasOwnProperty(l)&&(k=!0,Qe.Pa(g,l,Se(l,h[l])));k||Qe.Pa(g,"default",e)}};function Se(a,b){var c=wc(a,b);c.vtp_permissionName=a;c.vtp_createPermissionError=Re;return xc(c)}function Re(a,b,c){return new id(a,b,c)};var Ue=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Ve=function(a){return encodeURIComponent(a)},We=function(a,b){if(!a)return!1;var c=vb(N(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var Q=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null},Xe=function(a,b){Qa(a,b)},Ye=function(a){return ya(a)},Ze=function(a,b){return va(a,b)},$e=function(){return!1};var af=function(a){var b={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||mb(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};b["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"";return b},bf=function(a){Mc.hasOwnProperty("autoEventsSettings")||(Mc.autoEventsSettings={});var b=Mc.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},cf=function(a,b,c,d){var e=bf(a),g=Fa(e,b,d);e[b]=
c(g)},df=function(a,b,c){var d=bf(a);return Fa(d,b,c)};var ff=function(a,b){if(!ef)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!B.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);return null},gf=!1;
if(B.querySelectorAll)try{var hf=B.querySelectorAll(":root");hf&&1==hf.length&&hf[0]==B.documentElement&&(gf=!0)}catch(a){}var ef=gf;var jf=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},mf=function(a,b,c,d){var e=kf(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=lf(e,function(a){return a.Dd},b);if(1===e.length)return e[0].id;e=lf(e,function(a){return a.se},c);return e[0]?e[0].id:void 0}},pf=function(a,b,c,d,e,
g){c=c||"/";var h=d=d||"auto",k=c;if(nf.test(document.location.hostname)||"/"===k&&of.test(h))return!1;g&&(b=encodeURIComponent(b));var l=b;l&&1200<l.length&&(l=l.substring(0,1200));b=l;var m=a+"="+b+"; path="+c+"; ";void 0!==e&&(m+="expires="+e.toUTCString()+"; ");if("auto"===d){var n=!1,p;a:{var q=[],r=document.location.hostname.split(".");if(4===r.length){var u=r[r.length-1];if(parseInt(u,10).toString()===u){p=["none"];break a}}for(var t=r.length-2;0<=t;t--)q.push(r.slice(t).join("."));q.push("none");
p=q}for(var A=p,C=0;C<A.length&&!n;C++)n=pf(a,b,c,A[C],e);return n}d&&"none"!==d&&(m+="domain="+d+";");var D=document.cookie;document.cookie=m;return D!=document.cookie||0<=jf(a).indexOf(b)};function lf(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function kf(a,b){for(var c=[],d=jf(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),Dd:1*k[0]||1,se:1*k[1]||1}))}}return c}var of=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,nf=/(^|\.)doubleclick\.net$/i;var qf=function(){for(var a=eb.userAgent+(B.cookie||"")+(B.referrer||""),b=a.length,c=z.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Da()/1E3)].join(".")},tf=function(a,b,c,d){var e=rf(b);return mf(a,e,sf(c),d)};function rf(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length}
function sf(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1}function uf(a,b){var c=""+rf(a),d=sf(b);1<d&&(c+="-"+d);return c};var vf=["1"],wf={},Af=function(a,b,c){var d=xf(a);wf[d]||yf(d,b,c)||(zf(d,qf(),b,c),yf(d,b,c))};function zf(a,b,c,d){var e;e=["1",uf(c,d),b].join(".");pf(a,e,d,c,new Date(Da()+7776E6))}function yf(a,b,c){var d=tf(a,b,c,vf);d&&(wf[a]=d);return d}function xf(a){return(a||"_gcl")+"_au"};function Bf(){for(var a=Cf,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Df(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var Cf,Ef,Ff=function(a){Cf=Cf||Df();Ef=Ef||Bf();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,p=k&63;e||(p=64,d||(n=64));b.push(Cf[l],Cf[m],Cf[n],Cf[p])}return b.join("")},Gf=function(a){function b(b){for(;d<a.length;){var c=a.charAt(d++),e=Ef[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("Unknown base64 encoding at char: "+c);}return b}Cf=Cf||Df();Ef=Ef||
Bf();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Hf;function If(a,b){if(!a||b===B.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}var Jf=function(){var a=gb("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Kf=/(.*?)\*(.*?)\*(.*)/,Lf=/([^?#]+)(\?[^#]*)?(#.*)?/,Mf=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Of=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Ff(String(d))))}var e=b.join("*");return["1",Nf(e),e].join("*")},Nf=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:
b),a].join("*"),d;if(!(d=Hf)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}Hf=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Hf[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},Qf=function(){return function(a){var b=N(z.location.href),c=b.search.replace("?",""),d=ub(c,"_gl",!0)||"";a.query=Pf(d)||{};var e=vb(b,"fragment").match(Mf);a.fragment=Pf(e&&e[3]||"")||{}}},Pf=function(a){var b;b=void 0===b?3:b;try{if(a){var c=Kf.exec(a);if(c&&
"1"===c[1]){var d=c[3],e;a:{for(var g=c[2],h=0;h<b;++h)if(g===Nf(d,h)){e=!0;break a}e=!1}if(e){for(var k={},l=d?d.split("*"):[],m=0;m<l.length;m+=2)k[l[m]]=Gf(l[m+1]);return k}}}}catch(n){}};
function Rf(a,b,c){function d(a){var b=a,c=Mf.exec(b),d=b;if(c){var e=c[2],g=c[4];d=c[1];g&&(d=d+e+g)}a=d;var h=a.charAt(a.length-1);a&&"&"!==h&&(a+="&");return a+l}c=void 0===c?!1:c;var e=Lf.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function Sf(a,b,c){for(var d={},e={},g=Jf().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&If(k.domains,b)&&(k.fragment?Ha(e,k.callback()):Ha(d,k.callback()))}if(Ia(d)){var l=Of(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],p=!1,q=0;q<n.length;q++){var r=n[q];if("_gl"===r.name){r.setAttribute("value",l);p=!0;break}}if(!p){var u=B.createElement("input");u.setAttribute("type","hidden");u.setAttribute("name","_gl");u.setAttribute("value",
l);a.appendChild(u)}}else if("post"===m){var t=Rf(l,a.action);sb.test(t)&&(a.action=t)}}}else Tf(l,a,!1)}if(!c&&Ia(e)){var A=Of(e);Tf(A,a,!0)}}function Tf(a,b,c){if(b.href){var d=Rf(a,b.href,void 0===c?!1:c);sb.test(d)&&(b.href=d)}}
var Uf=function(a){try{var b;a:{for(var c=a.target||a.srcElement||{},d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||Sf(e,e.hostname,!1)}}catch(h){}},Vf=function(a){try{var b=a.target||a.srcElement||{};if(b.action){var c=vb(N(b.action),"host");Sf(b,c,!0)}}catch(d){}},Wf=function(a,b,c,d){var e=Jf();e.init||(kb(B,"mousedown",Uf),kb(B,"keyup",Uf),kb(B,"submit",Vf),e.init=!0);var g={callback:a,
domains:b,fragment:"fragment"===c,forms:!!d};Jf().decorators.push(g)};var Xf=/^\w+$/,Yf=/^[\w-]+$/,Zf=/^~?[\w-]+$/,$f={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"},bg=function(a){var b=jf(a,B.cookie),c=[];if(!b||0==b.length)return c;for(var d=0;d<b.length;d++){var e=b[d].split(".");3==e.length&&"GCL"==e[0]&&e[1]&&c.push(e[2])}return ag(c)};function cg(a){return a&&"string"==typeof a&&a.match(Xf)?a:"_gcl"}
var dg=function(a){if(a){if("string"==typeof a){var b=cg(a);return{dc:b,aw:b,gf:b,ha:b}}if(a&&"object"==typeof a)return{dc:cg(a.dc),aw:cg(a.aw),gf:cg(a.gf),ha:cg(a.ha)}}return{dc:"_gcl",aw:"_gcl",gf:"_gcl",ha:"_gcl"}},eg=function(){var a=N(z.location.href),b={},c=function(a,c){b[c]||(b[c]=[]);b[c].push(a)},d=vb(a,"query",!1,void 0,"gclid"),e=vb(a,"query",!1,void 0,"gclsrc");if(!d||!e){var g=a.hash.replace("#","");d=d||ub(g,"gclid");e=e||ub(g,"gclsrc")}if(void 0!==d&&d.match(Yf))switch(e){case void 0:c(d,
"aw");break;case "aw.ds":c(d,"aw");c(d,"dc");break;case "ds":c(d,"dc");break;case "gf":c(d,"gf");break;case "ha":c(d,"ha")}var h=vb(a,"query",!1,void 0,"dclid");h&&c(h,"dc");return b},gg=function(a){function b(a,b){var g=fg(a,c);g&&pf(g,b,e,d,h,!0)}a=a||{};var c=dg(a.prefix),d=a.domain||"auto",e=a.path||"/",g=Da(),h=new Date(g+7776E6),k=Math.round(g/1E3),l=eg(),m=function(a){return["GCL",k,a].join(".")};l.aw&&(!0===a.xf?b("aw",m("~"+l.aw[0])):b("aw",m(l.aw[0])));l.dc&&b("dc",m(l.dc[0]));l.gf&&b("gf",
m(l.gf[0]));l.ha&&b("ha",m(l.ha[0]))},fg=function(a,b){var c=$f[a];if(void 0!==c){var d=b[a];if(void 0!==d)return d+c}},hg=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)},ig=function(a,b,c,d,e){if(ua(b)){var g=dg(e);Wf(function(){for(var b={},c=0;c<a.length;++c){var d=fg(a[c],g);if(d){var e=jf(d,B.cookie);e.length&&(b[d]=e.sort()[e.length-1])}}return b},b,c,d)}},ag=function(a){return a.filter(function(a){return Zf.test(a)})};var jg=/^\d+\.fls\.doubleclick\.net$/;function kg(a){var b=N(z.location.href),c=vb(b,"host",!1);if(c&&c.match(jg)){var d=vb(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
var lg=function(a){var b=kg("gclaw");if(b)return b.split(".");var c=dg(a);if("_gcl"==c.aw){var d=eg().aw||[];if(0<d.length)return d}var e=fg("aw",c);return e?bg(e):[]},mg=function(a){var b=kg("gcldc");if(b)return b.split(".");var c=dg(a);if("_gcl"==c.dc){var d=eg().dc||[];if(0<d.length)return d}var e=fg("dc",c);return e?bg(e):[]},ng=function(a){var b=dg(a);if("_gcl"==b.ha){var c=eg().ha||[];if(0<c.length)return c}return bg(b.ha+"_ha")},og=function(){var a=kg("gac");if(a)return decodeURIComponent(a);
for(var b=[],c=B.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var g=c[e].match(d);g&&b.push({Db:g[1],value:g[2]})}var h={};if(b&&b.length)for(var k=0;k<b.length;k++){var l=b[k].value.split(".");"1"==l[0]&&3==l.length&&l[1]&&(h[b[k].Db]||(h[b[k].Db]=[]),h[b[k].Db].push({timestamp:l[1],Kd:l[2]}))}var m=[],n;for(n in h)if(h.hasOwnProperty(n)){for(var p=[],q=h[n],r=0;r<q.length;r++)p.push(q[r].Kd);p=ag(p);p.length&&m.push(n+":"+p.join(","))}return m.join(";")},pg=function(a,
b,c){Af(a,b,c);var d=wf[xf(a)],e=eg().dc||[];if(d&&0<e.length){var g=Mc.joined_au=Mc.joined_au||{},h=a||"_gcl";if(!g[h]){for(var k=!1,l=0;l<e.length;l++){var m="http://ad.doubleclick.net/ddm/regclk";m+="?gclid="+e[l]+"&auiddc="+d;rb(m);k=!0}if(k){var n=xf(a);wf[n]&&zf(n,wf[n],b,c);g[h]=!0}}}};var rg={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:qg()};function qg(){if(3===Lc.Na.length)return"g";return"g";return"G"}var sg=function(a){var b=Lc.w.split("-"),c=b[0].toUpperCase(),d=rg[c]||"i",e=a&&"GTM"===c?b[1]:"",g;if(3===Lc.Na.length){var h;a:{h=De()?"s":"o";break a;h="w"}g="2"+h}else g="";return g+d+Lc.Na+e};
var tg=function(a){return!(void 0===a||null===a||0===(a+"").length)},ug=function(a,b){var c;if(2===b.J)return a("ord",wa(1E11,1E13)),!0;if(3===b.J)return a("ord","1"),a("num",wa(1E11,1E13)),!0;if(4===b.J)return tg(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.J)c="1";else if(6===b.J)c=b.Gc;else return!1;tg(c)&&a("qty",c);tg(b.jb)&&a("cost",b.jb);tg(b.Eb)&&a("ord",b.Eb);return!0},vg=encodeURIComponent,wg=function(a,b){function c(a,b,c){g.hasOwnProperty(a)||(b+="",e+=";"+a+"="+(c?b:vg(b)))}var d=a.lb,
e=a.protocol;e+=a.$a?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+vg(d)+(";type="+vg(a.mb))+(";cat="+vg(a.va));var g=a.xd||{},h;for(h in g)g.hasOwnProperty(h)&&(e+=";"+vg(h)+"="+vg(g[h]+""));if(ug(c,a)){tg(a.Gb)&&c("u",a.Gb);tg(a.tran)&&c("tran",a.tran);c("gtm",sg());!1===a.Zc&&c("npa","1");if(a.ib){var k=mg(a.ia);k&&k.length&&c("gcldc",k.join("."));var l=lg(a.ia);l&&l.length&&c("gclaw",l.join("."));var m=og();m&&c("gac",m);
Af(a.ia);var n=wf[xf(a.ia)];n&&c("auiddc",n);}tg(a.vb)&&c("prd",a.vb,!0);for(var p in a.Ga)a.Ga.hasOwnProperty(p)&&c(p,a.Ga[p]);e+=b||"";tg(a.Wa)&&c("~oref",a.Wa);a.$a?jb(e+"?",a.S):G(e+"?",a.S,a.la)}else I(a.la)};
var yg=function(a){if(a)try{if(a.conversion_id&&a.conversion_data){var b="/pagead/conversion/"+xg(a.conversion_id)+"/?",c=xg(JSON.stringify(a.conversion_data)),d="https://www.googletraveladservices.com/travel/flights/clk"+b+"conversion_data="+c;if(a.conversionLinkerEnabled){var e;a:{var g=dg(a.conversionPrefix);if("_gcl"==g.gf){var h=eg().gf||[];if(0<h.length){e=h;break a}}var k=fg("gf",g);e=k?bg(k):[]}var l=e;if(l&&l.length)for(var m=0;m<l.length;m++)d+="&gclgf="+xg(l[m])}G(d,a.onSuccess,a.onFailure)}}catch(n){}},
xg=function(a){return null===a||void 0===a||0===String(a).length?"":encodeURIComponent(String(a))};var zg=!!z.MutationObserver,Ag=void 0,Bg=function(a){if(!Ag){var b=function(){var a=B.body;if(a)if(zg)(new MutationObserver(function(){for(var a=0;a<Ag.length;a++)I(Ag[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;kb(a,"DOMNodeInserted",function(){b||(b=!0,I(function(){b=!1;for(var a=0;a<Ag.length;a++)I(Ag[a])}))})}};Ag=[];B.body?b():I(b)}Ag.push(a)};var Cg=/\./g,Dg=/\*/g;var Ug="www.googletagmanager.com/gtm.js";Ug="www.googletagmanager.com/gtag/js";
var Vg=Ug,Wg=function(a,b,c,d){kb(a,b,c,d)},Xg=function(a,b){return z.setTimeout(a,b)},S=function(a,b,c){if(De()){b&&I(b)}else return ib(a,b,c)},Yg=function(){return z.location.href},Zg=function(a){return vb(N(a),"fragment")},$g=function(a,b,c,d,e){return vb(a,b,c,d,e)},U=function(a,b){return Wc(a,b||2)},ah=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return z["dataLayer"].push(a)},bh=function(a,
b){z[a]=b},V=function(a,b,c){b&&(void 0===z[a]||c&&!z[a])&&(z[a]=b);return z[a]},ch=function(a,b,c){return jf(a,b,void 0===c?!0:!!c)},dh=function(a,b,c){gg({prefix:a,path:b,domain:c})},eh=function(a,b,c,d){var e=Qf(),g=Jf();g.data||(g.data={query:{},fragment:{}},e(g.data));var h={},k=g.data;k&&(Ha(h,k.query),Ha(h,k.fragment));for(var l=dg(b),m=0;m<a.length;++m){var n=a[m];if(void 0!==$f[n]){var p=fg(n,l),q=h[p];if(q){var r=Math.min(hg(q),Da()),u;b:{for(var t=
r,A=jf(p,B.cookie),C=0;C<A.length;++C)if(hg(A[C])>t){u=!0;break b}u=!1}u||pf(p,q,c,d,new Date(r+7776E6),!0)}}}},fh=function(a,b,c,d,e){ig(a,b,c,d,e);},gh=function(a,b,c){var d;a:{var e;e=c||100;for(var g={},h=0;h<b.length;h++)g[b[h]]=!0;for(var k=a,l=0;k&&l<=e;l++){if(g[String(k.tagName).toLowerCase()]){d=k;break a}k=k.parentElement}d=null}return d},X=function(a,b,c,d){var e=
!d&&"http:"==z.location.protocol;e&&(e=2!==hh());return(e?b:a)+c},ih=function(a,b){if(De()){b&&I(b)}else jb(a,b)};
var jh=function(a){var b=0;return b},kh=function(a){},lh=function(a){var b=!1;return b},mh=function(a,b){var c;a:{if(a&&
ua(a))for(var d=0;d<a.length;d++)if(a[d]&&b(a[d])){c=a[d];break a}c=void 0}return c},nh=function(a,b,c,d){cf(a,b,c,d)},oh=function(a,b,c){return df(a,b,c)},ph=function(a){return!!df(a,"init",!1)},qh=function(a){bf(a).init=!0};
var hh=function(){var a=Vg;if(fb){var b=fb.toLowerCase();if(0===b.indexOf("https://"))return 2;if(0===b.indexOf("http://"))return 3}a=a.toLowerCase();for(var c="https://"+a,d="http://"+a,e=1,g=B.getElementsByTagName("script"),h=0;h<g.length&&100>h;h++){var k=g[h].src;if(k){k=k.toLowerCase();if(0===k.indexOf(d))return 3;1===e&&0===k.indexOf(c)&&(e=2)}}return e};
var sh=function(a,b){return Yc(a,b,void 0)},th=function(a,b,c,d){var e={config:a,gtm:sg(void 0)};c&&(Af(d),e.auiddc=wf[xf(d)]);b&&(e.loadInsecure=b);V("__dc_ns_processor",[]).push(e);S((b?"http":"https")+"://www.googletagmanager.com/dclk/ns/v1.js")};
var uh=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Vg;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";if(b)for(var e in b)b[e]&&b.hasOwnProperty(e)&&(d+="&"+e+"="+encodeURIComponent(b[e]));S(X("https://","http://",d))};
var wh=function(a,b,c){a instanceof xe.Rc&&(a=a.resolve(xe.Ce(b,c)),b=qa);return{nb:a,S:b}};var Jh=function(a,b,c){this.n=a;this.t=b;this.p=c},Kh=function(){this.c=1;this.e=[];this.p=null};function Lh(a){var b=Mc,c=b.gss=b.gss||{};return c[a]=c[a]||new Kh}var Mh=function(a,b){Lh(a).p=b},Nh=function(a,b,c){var d=Math.floor(Da()/1E3);Lh(a).e.push(new Jh(b,d,c))},Oh=function(a){};var Xh=window,Yh=document,Zh=function(a){var b=Xh._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Xh["ga-disable-"+a])return!0;try{var c=Xh.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=jf("AMP_TOKEN",Yh.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return!1};var di=function(a){if(1===Lh(a).c){Lh(a).c=2;var b=encodeURIComponent(a);ib(("http:"!=z.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},ei=function(a,b){};var Z={a:{}};
Z.a.gtagha=["google"],function(){function a(a){function b(a,b){void 0!==b&&c.push(a+"="+b)}if(void 0===a)return"";var c=[];b("hct_base_price",a.jc);b("hct_booking_xref",a.kc);b("hct_checkin_date",a.Rd);b("hct_checkout_date",a.Sd);b("hct_currency_code",a.Td);b("hct_partner_hotel_id",a.mc);b("hct_total_price",a.nc);return c.join(";")}function b(b,c,d,k){var e=encodeURIComponent(b),g=encodeURIComponent(a(c)),h="https://www.googletraveladservices.com/travel/clk/pagead/conversion/"+e+"/?data="+g;d&&(h+=
ng(k).map(function(a){return"&gclha="+encodeURIComponent(a)}).join(""));return h}function c(a,b,c,d){var e={};sa(a)?e.kc=a:"number"===typeof a&&(e.kc=String(a));sa(c)&&(e.Td=c);sa(b)?e.nc=e.jc=b:"number"===typeof b&&(e.nc=e.jc=String(b));if(!ua(d)||0==d.length)return e;var g=d[0];if(!Pa(g))return e;sa(g.id)?e.mc=g.id:"number"===typeof g.id&&(e.mc=String(g.id));sa(g.start_date)&&(e.Rd=g.start_date);sa(g.end_date)&&(e.Sd=g.end_date);return e}function d(a){var b=Oc,e=a.vtp_gtmOnSuccess,k=a.vtp_gtmOnFailure,
l=a.vtp_conversionId,m=l.containerId,n=function(a){return Yc(a,m,l.id)},p=!1!==n("conversion_linker"),q=n("conversion_cookie_prefix");if("gtag.config"===b)p&&dh(q),I(e);else if("purchase"===b){var r=c(n("transaction_id"),n("value"),n("currency"),n("items"));d.Pe(l.W[0],r,p,q,e,k)}else I(k)}d.Pe=function(a,c,d,k,l,m){if(/^\d+$/.test(a)){var e=b(a,c,d,k);G(e,l,m)}else I(m)};Z.__gtagha=d;Z.__gtagha.g="gtagha";Z.__gtagha.h=!0;Z.__gtagha.b=0}();Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.g="e";Z.__e.h=!0;Z.__e.b=0})(function(){return Oc})}();


Z.a.v=["google"],function(){(function(a){Z.__v=a;Z.__v.g="v";Z.__v.h=!0;Z.__v.b=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=U(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();





Z.a.gtagaw=["google"],function(){var a=!1,b=!1,c=[],d=["aw","dc"],e="send_to aw_remarketing aw_remarketing_only custom_params send_page_view language value currency transaction_id user_id conversion_linker conversion_cookie_prefix page_location page_referrer phone_conversion_number phone_conversion_callback phone_conversion_css_class items aw_merchant_id aw_feed_country aw_feed_language discount disable_merchant_reported_purchases allow_ad_personalization_signals".split(" "),g=function(a){var b=V("google_trackConversion"),
c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},h=function(){for(;0<c.length;)g(c.shift())},k=function(){a||(a=!0,S(X("https://","http://","www.googleadservices.com/pagead/conversion_async.js"),function(){h();c={push:g}},function(){h();a=!1}))},l=function(a,c,d,e){if(De()){}else if(c){var g=a.W[0],h=a.W[1],k=V("_googWcmImpl",function(){k.q=k.q||[];k.q.push(arguments)});V("_googWcmAk",g);b||(b=!0,S(X("https://",
"http://","www.gstatic.com/wcm/loader.js")));var l={ak:g,cl:h};void 0===d&&(l.autoreplace=c);k(2,d,l,c,e,new Date,e)}},m=function(a){if(a){for(var b=[],c=0;c<a.length;++c){var d=a[c];d&&b.push({item_id:d.id,quantity:d.quantity,value:d.price,start_date:d.start_date,end_date:d.end_date})}return b}},n=function(a){var b=a.vtp_conversionId,g=Oc,h="gtag.config"==g,n=b.W[0],p=b.W[1],C=void 0!==p,D=b.containerId,L=C?b.id:void 0,E=function(a){return Yc(a,D,L)},F=!1!==E("conversion_linker"),J=E("conversion_cookie_prefix");
if(h){var H=E("linker")||{};F&&((H.accept_incoming||!1!==H.accept_incoming&&H.domains)&&eh(d,J),dh(J));H.domains&&fh(d,H.domains,H.url_position,!!H.decorate_forms,J);if(C){var K=E("phone_conversion_number"),R=E("phone_conversion_callback"),ja=E("phone_conversion_css_class"),W=E("phone_conversion_options");l(b,K,R||ja,W)}}var ba=!1===E("aw_remarketing")||!1===E("send_page_view");if(!h||!C&&!ba)if(!0===E("aw_remarketing_only")&&(C=!1),!1!==E("allow_ad_personalization_signals")||C){var M={google_conversion_id:n,
google_remarketing_only:!C,onload_callback:a.vtp_gtmOnSuccess,gtm_onFailure:a.vtp_gtmOnFailure,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:p,google_conversion_language:E("language"),google_conversion_value:E("value"),google_conversion_currency:E("currency"),google_conversion_order_id:E("transaction_id"),google_user_id:E("user_id"),google_conversion_page_url:E("page_location"),google_conversion_referrer_url:E("page_referrer"),google_gtm:sg(void 0)};
!1===E("allow_ad_personalization_signals")&&(M.google_allow_ad_personalization_signals=!1);M.google_read_gcl_cookie_opt_out=!F;F&&J&&(Pa(J)?M.google_gcl_cookie_prefix=J.aw:M.google_gcl_cookie_prefix=J);var T=function(){var a=E("custom_params"),b={event:g};if(ua(a)){for(var c=0;c<a.length;++c){var d=a[c],h=E(d);void 0!==h&&(b[d]=h)}return b}var k=E("eventModel");if(!k)return null;Qa(k,b);for(var l=0;l<e.length;++l)delete b[e[l]];return b}();T&&(M.google_custom_params=T);!C&&E("items")&&(M.google_gtag_event_data=
{items:E("items"),value:E("value")});if(C&&"purchase"==g){E("aw_merchant_id")&&(M.google_conversion_merchant_id=E("aw_merchant_id"),M.google_basket_feed_country=E("aw_feed_country"),M.google_basket_feed_language=E("aw_feed_language"),M.google_basket_discount=E("discount"),M.google_basket_transaction_type=g,M.google_disable_merchant_reported_conversions=!0===E("disable_merchant_reported_purchases"),De()&&(M.google_disable_merchant_reported_conversions=!0));var O=m(E("items"));O&&(M.google_conversion_items=
O)}c.push(M)}k()};Z.__gtagaw=n;Z.__gtagaw.g="gtagaw";Z.__gtagaw.h=!0;Z.__gtagaw.b=0}();
Z.a.get=["google"],function(){(function(a){Z.__get=a;Z.__get.g="get";Z.__get.h=!0;Z.__get.b=0})(function(a){if(a.vtp_isAutoTag){for(var b=String(a.vtp_trackingId),c=Oc||"",d={},e=0;e<be.length;e++){var g=sh(be[e],b);void 0!==g&&(d[be[e]]=g)}var h=sh("custom_params",b);if(ua(h))for(var k=0;k<h.length;k++){var l=h[k],m=sh(l,b);void 0!==m&&(d[l]=m)}else{var n=U("eventModel");Qa(n,d)}var p=Qa(d,void 0);di(b);Nh(b,c,p);Oh(b)}else{var q=a.vtp_settings,r=q.eventParameters,u=q.userProperties,t=Q(a.vtp_eventParameters,
"name","value");Qa(t,r);var A=Q(a.vtp_userProperties,"name","value");Qa(A,u);r.user_properties=u;var C=String(q.streamId),D=String(a.vtp_eventName);di(C);Nh(C,D,r);Oh(C)}a.vtp_gtmOnSuccess()})}();


Z.a.gtagfl=[],function(){function a(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{containerId:"DC-"+b[1],Lc:b[3]?a:"",Uc:b[1],Tc:b[3]||"",va:b[4]||"",J:c}}}function b(a,b){function c(b,c,e){void 0!==e&&0!==(e+"").length&&d.push(b+c+":"+a(e+""))}var d=[],e=b("items")||[];if(ua(e))for(var g=0;g<e.length;g++){var n=e[g],p=g+1;c("i",p,n.id);c("p",p,n.price);c("q",p,n.quantity);
c("c",p,b("country"));c("l",p,b("language"))}return d.join("|")}function c(a,b,c){var d=/^u([1-9]\d?|100)$/,e=a("custom_map")||{},g=ad(b,c),h={},p={};if(Pa(e))for(var q in e)if(e.hasOwnProperty(q)&&d.test(q)){var r=e[q];sa(r)&&(h[q]=r)}for(var u=0;u<g.length;u++){var t=g[u];d.test(t)&&(h[t]=t)}for(var A in h)h.hasOwnProperty(A)&&(p[A]=a(h[A]));return p}var d=["aw","dc"];(function(a){Z.__gtagfl=a;Z.__gtagfl.g="gtagfl";Z.__gtagfl.h=!0;Z.__gtagfl.b=0})(function(e){var g=e.vtp_gtmOnSuccess,h=e.vtp_gtmOnFailure,
k=a(e.vtp_targetId);if(k){var l=function(a){return Yc(a,k.containerId,k.Lc||void 0)},m=!1!==l("conversion_linker"),n=l("conversion_cookie_prefix"),p=l("dc_natural_search"),q=3===hh();if("gtag.config"===Oc){var r=l("linker")||{};m&&((r.accept_incoming||!1!==r.accept_incoming&&r.domains)&&eh(d,n),dh(n),pg(n,void 0,void 0));r.domains&&fh(d,r.domains,r.url_position,!!r.decorate_forms,n);if(p&&p.exclusion_parameters&&p.engines){}I(g)}else{var u=
{},t=l("dc_custom_params");if(Pa(t))for(var A in t)if(t.hasOwnProperty(A)){var C=t[A];void 0!==C&&null!==C&&(u[A]=C)}var D="";if(5===k.J||6===k.J)D=b(Ve,l);var L=c(l,k.containerId,k.Lc),E=!0===l("allow_custom_scripts");if(De()&&E){E=!1}var F={va:k.va,ib:m,ia:n,jb:l("value"),J:k.J,xd:u,lb:k.Uc,mb:k.Tc,la:h,S:g,Wa:wb(N(Yg())),vb:D,protocol:q?"http:":"https:",Gc:l("quantity"),$a:E,sessionId:l("session_id"),Eb:l("transaction_id"),
Ga:L,Zc:!1!==l("allow_ad_personalization_signals")};wg(F,void 0)}}else I(h)})}();
Z.a.gtaggf=["google"],function(){var a=/.*\.google\.com(:\d+)?\/booking\/flights.*/,b=function(a){if(a){for(var b=[],c=0,g=0;g<a.length;++g){var h=a[g];!h||void 0!==h.category&&""!==h.category&&"FlightSegment"!==h.category||(b[c]={cabin:h.travel_class,fare_product:h.fare_product,booking_code:h.booking_code,flight_number:h.flight_number,origin:h.origin,destination:h.destination,departure_date:h.start_date},c++)}return b}};(function(a){Z.__gtaggf=a;Z.__gtaggf.g="gtaggf";Z.__gtaggf.h=!0;Z.__gtaggf.b=
0})(function(c){var d=Oc,e=c.vtp_gtmOnSuccess,g=c.vtp_gtmOnFailure,h=c.vtp_conversionId,k=h.W[0],l=h.containerId,m=function(a){return Yc(a,l,h.id)},n=!1!==m("conversion_linker"),p=m("conversion_cookie_prefix");if("gtag.config"===d)n&&dh(p),I(e);else{var q={conversion_id:k,onFailure:g,onSuccess:e,conversionLinkerEnabled:n,conversionPrefix:p};if("purchase"===d){var r=a.test(Yg()),u={partner_id:k,trip_type:m("trip_type"),total_price:m("value"),currency:m("currency"),is_direct_booking:r,flight_segment:b(m("items"))},
t=m("passengers");t&&"object"===typeof t&&(u.passengers_total=t.total,u.passengers_adult=t.adult,u.passengers_child=t.child,u.passengers_infant_in_seat=t.infant_in_seat,u.passengers_infant_in_lap=t.infant_in_lap);q.conversion_data=u}yg(q)}})}();


Z.a.gtagua=["google"],function(){var a,b={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},c={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",
fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},d={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},e={cookie_name:1,cookie_expires:"duration",levels:1},g={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},
h=function(a,b,c,d){if(void 0!==c)if(g[b]&&(c=Aa(c)),"anonymize_ip"!=b||c||(c=void 0),1===a)d[k(b)]=c;else if(sa(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},k=function(a){return a&&sa(a)?a.replace(/(_[a-z])/g,function(a){return a[1].toUpperCase()}):a},l=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},m=function(a,e,g){var k={},m={},n={},p;var q=sh("experiments",a);if(ua(q)){for(var t=[],r=0;r<q.length;r++){var u=q[r];if(void 0!=u){var A=u.id,ja=u.variant;void 0!=
A&&void 0!=ja&&t.push(String(A)+"."+String(ja))}}p=0<t.length?t.join("!"):void 0}else p=void 0;p&&l(m,"exp",p);var W=sh("custom_map",a);if(Pa(W))for(var ba in W)if(W.hasOwnProperty(ba)&&/^(dimension|metric)\d+$/.test(ba)){var M=sh(W[ba],a);void 0!==M&&l(m,ba,M)}for(var T=ad(a,void 0),O=0;O<T.length;++O){var Y=T[O],ca=sh(Y,a);d.hasOwnProperty(Y)?h(d[Y],Y,ca,k):c.hasOwnProperty(Y)?h(c[Y],Y,ca,m):b.hasOwnProperty(Y)?h(b[Y],Y,ca,n):/^(dimension|metric|content_group)\d+$/.test(Y)&&h(1,Y,ca,m)}var da=String(Oc);
l(n,"cookieDomain","auto");l(m,"forceSSL",!0);var xa="general";0<=Ze("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),da)?xa="ecommerce":0<=Ze("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),da)?xa="engagement":"exception"==da&&(xa="error");l(k,"eventCategory",xa);0<=Ze(["view_item","view_item_list","view_promotion","view_search_results"],
da)&&l(m,"nonInteraction",!0);"login"==da||"sign_up"==da||"share"==da?l(k,"eventLabel",sh("method",a)):"search"==da||"view_search_results"==da?l(k,"eventLabel",sh("search_term",a)):"select_content"==da&&l(k,"eventLabel",sh("content_type",a));var za=k.linker||{};if(za.accept_incoming||0!=za.accept_incoming&&za.domains)n.allowLinker=!0;if(!1===sh("allow_display_features",a)||!1===sh("allow_ad_personalization_signals",a))m.allowAdFeatures=!1;n.name=e;m["&gtm"]=sg(!0);m.hitCallback=g;k.R=m;k.ac=n;return k},
n=function(a){function b(a){var b=Qa(a,void 0);b.list=a.list_name;b.listPosition=a.list_position;b.position=a.list_position||a.creative_slot;b.creative=a.creative_name;return b}function c(a){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&c.push(b(a[d]));return c.length?c:void 0}function d(a){return{id:e("transaction_id"),affiliation:e("affiliation"),revenue:e("value"),tax:e("tax"),shipping:e("shipping"),coupon:e("coupon"),list:e("list_name")||a}}for(var e=function(b){return Yc(b,a,void 0)},g=e("items"),
h,k=0;g&&k<g.length&&!(h=g[k].list_name);k++);var m=e("custom_map");if(Pa(m))for(k=0;g&&k<g.length;++k){var n=g[k],p;for(p in m)m.hasOwnProperty(p)&&/^(dimension|metric)\d+$/.test(p)&&l(n,p,n[m[p]])}var q=null,r=Oc,u=e("promotions");"purchase"==r||"refund"==r?q={action:r,sa:d(),ma:c(g)}:"add_to_cart"==r?q={action:"add",ma:c(g)}:"remove_from_cart"==r?q={action:"remove",ma:c(g)}:"view_item"==r?q={action:"detail",sa:d(h),ma:c(g)}:"view_item_list"==r?q={action:"impressions",Xd:c(g)}:"view_promotion"==
r?q={action:"promo_view",wb:c(u)}:"select_content"==r&&u&&0<u.length?q={action:"promo_click",wb:c(u)}:"select_content"==r?q={action:"click",sa:{list:e("list_name")||h},ma:c(g)}:"begin_checkout"==r||"checkout_progress"==r?q={action:"checkout",ma:c(g),sa:{step:"begin_checkout"==r?1:e("checkout_step"),option:e("checkout_option")}}:"set_checkout_option"==r&&(q={action:"checkout_option",sa:{step:e("checkout_step"),option:e("checkout_option")}});q&&(q.cf=e("currency"));return q},p={},q=function(a,b){var c=
p[a];p[a]=Qa(b,void 0);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(d in c)if(c.hasOwnProperty(d)&&c[d]!==b[d])return!0;return!1},r=function(b){var c=b.vtp_trackingId,d=ud(void 0),g="gtag_"+c.split("-").join("_"),p=function(a){var b=[].slice.call(arguments,0);b[0]=g+"."+b[0];d.apply(window,b)},r=function(){var a=function(a,b){for(var c=0;b&&c<b.length;c++)p(a,b[c])},b=n(c);if(b){var d=b.action;if("impressions"==d)a("ec:addImpression",b.Xd);else if("promo_click"==
d||"promo_view"==d){var e=b.wb;a("ec:addPromo",b.wb);e&&0<e.length&&"promo_click"==d&&p("ec:setAction",d)}else a("ec:addProduct",b.ma),p("ec:setAction",d,b.sa)}},u=function(){if(De()){}else{var a=sh("optimize_id",c);a&&(p("require",a,{dataLayer:"dataLayer"}),p("require","render"))}},F=m(c,g,b.vtp_gtmOnSuccess);q(g,F.ac)&&d(function(){td()&&td().remove(g)});d("create",c,F.ac);(function(){var a=sh("custom_map",c);
d(function(){if(Pa(a)){var b=F.R,c=td().getByName(g),d;for(d in a)if(a.hasOwnProperty(d)&&/^(dimension|metric)\d+$/.test(d)){var e=c.get(k(a[d]));l(b,d,e)}}})})();(function(a){if(a){var b={};if(Pa(a))for(var c in e)e.hasOwnProperty(c)&&h(e[c],c,a[c],b);p("require","linkid",b)}})(F.linkAttribution);var J=F.linker;J&&J.domains&&wd(g+".",J.domains,!!J.use_anchor,!!J.decorate_forms);var H=function(a,b,c){c&&(b=""+b);F.R[a]=b},K=Oc;"page_view"==K?(u(),p("send","pageview",F.R)):"gtag.config"==K?(u(),0!=
F.sendPageView&&p("send","pageview",F.R)):"screen_view"==K?p("send","screenview",F.R):"timing_complete"==K?(H("timingCategory",F.eventCategory,!0),H("timingVar",F.name,!0),H("timingValue",ya(F.value)),void 0!==F.eventLabel&&H("timingLabel",F.eventLabel,!0),p("send","timing",F.R)):"exception"==K?p("send","exception",F.R):(0<=Ze("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),K)&&(p("require",
"ec","ec.js"),r()),H("eventCategory",F.eventCategory,!0),H("eventAction",F.eventAction||K,!0),void 0!==F.eventLabel&&H("eventLabel",F.eventLabel,!0),void 0!==F.value&&H("eventValue",ya(F.value)),p("send","event",F.R));a||(a=!0,S("https://www.google-analytics.com/analytics.js",function(){td().loaded||b.vtp_gtmOnFailure()},b.vtp_gtmOnFailure))};Z.__gtagua=r;Z.__gtagua.g="gtagua";Z.__gtagua.h=!0;Z.__gtagua.b=
0}();


var fi={macro:function(a){if(xe.fb.hasOwnProperty(a))return xe.fb[a]}};fi.dataLayer=Xc;fi.onHtmlSuccess=xe.Zb(!0);fi.onHtmlFailure=xe.Zb(!1);fi.callback=function(a){Qc.hasOwnProperty(a)&&ra(Qc[a])&&Qc[a]();delete Qc[a]};fi.gd=function(){Mc[Lc.w]=fi;Rc=Z.a;uc=uc||xe;vc=hd};
fi.Yd=function(){Mc=z.google_tag_manager=z.google_tag_manager||{};if(Mc[Lc.w]){var a=Mc.zones;a&&a.unregisterChild(Lc.w)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)nc.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)qc.push(e[g]);for(var h=b.predicates||[],k=0;k<h.length;k++)pc.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],p={},q=0;q<n.length;q++)p[n[q][0]]=Array.prototype.slice.call(n[q],1);oc.push(p)}sc=Z;Te();fi.gd();we();ld=!1;md=0;if("interactive"==
B.readyState&&!B.createEventObject||"complete"==B.readyState)od();else{kb(B,"DOMContentLoaded",od);kb(B,"readystatechange",od);if(B.createEventObject&&B.documentElement.doScroll){var r=!0;try{r=!z.frameElement}catch(t){}r&&pd()}kb(z,"load",od)}oe=!1;"complete"===B.readyState?qe():kb(z,"load",qe);a:{
if(!Bd)break a;Ed();Hd=void 0;Id={};Fd={};Kd=void 0;Jd={};Gd="";Ld=Cd();z.setInterval(Ed,864E5);}Nc=(new Date).getTime()}};fi.Yd();

})()
